### ISSUE TITLE
Custom style repo

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#1008]
Discussion for making a new custom style repo:

## Content

- Keep it GitHub only?
- Usercss should override GitHub dark styles.
  - Should we talk about eventually removing these portions from GHD? Then we'd have to give the users a list of smaller usercss styles that should be installed together.

## UserCSS to include (so far)

(I also started adding "custom style posted" labels, but didn't get too far) See https://github.com/StylishThemes/GitHub-Dark/labels/custom%20style%20posted%20%F0%9F%8E%A8

- [Contribution graph](https://github.com/StylishThemes/GitHub-Dark/issues/1002)
- [Diff colors](https://github.com/StylishThemes/GitHub-Dark/issues/1006)

---

Poll, new repo name ([add more if you want](https://github.com/evenchange4/gh-polls-bot))

[![](https://api.gh-polls.com/poll/01DQTRT5J1RBWTSHR3MACXX6ES/Custom%20Override%20Styles)](https://api.gh-polls.com/poll/01DQTRT5J1RBWTSHR3MACXX6ES/Custom%20Override%20Styles/vote)
[![](https://api.gh-polls.com/poll/01DQTRT5J1RBWTSHR3MACXX6ES/Feature%20Override%20Styles)](https://api.gh-polls.com/poll/01DQTRT5J1RBWTSHR3MACXX6ES/Feature%20Override%20Styles/vote)
[![](https://api.gh-polls.com/poll/01DQTRT5J1RBWTSHR3MACXX6ES/GitHub-Dark-Extras)](https://api.gh-polls.com/poll/01DQTRT5J1RBWTSHR3MACXX6ES/GitHub-Dark-Extras/vote)
[![](https://api.gh-polls.com/poll/01DQTRT5J1RBWTSHR3MACXX6ES/GitHub-Dark-Features-No-One-But-Me-Wants)](https://api.gh-polls.com/poll/01DQTRT5J1RBWTSHR3MACXX6ES/GitHub-Dark-Features-No-One-But-Me-Wants/vote)
[![](https://api.gh-polls.com/poll/01DQTRT5J1RBWTSHR3MACXX6ES/Over%209000)](https://api.gh-polls.com/poll/01DQTRT5J1RBWTSHR3MACXX6ES/Over%209000/vote)

**Comment by the-j0k3r** [comment]
Actually thinking of it, best to make a general styles repo, this way we can add these to any style we support.

Possible names:

Custom Override Styles
Feature Override Styles
Override  Override  Styles Override Override <- dis one =)

>(I also started adding "custom style posted" labels, but didn't get too far)

I only added that label today thinking about this before hand, but yea theres others Im sure.

**Comment by the-j0k3r** [comment]
added label link I added another one, not sure about it though.

**Comment by the-j0k3r** [comment]
>Should we talk about eventually removing these portions from GHD? Then we'd have to give the users a list of smaller usercss styles that should be installed together.

I dont think its necessary (though we can but then where does it stop?), Some of these are for edge cases, people reporting it try to bolster their cases by saying many users want this (whatever the person reporting issue is asking for). Law of diminishing returns should apply...
 
With a well noted exception where colorblind users are concerned (a valid issue) which in any case we can provide these Feature Override Styles or whatever we wanna call them.

Also [when I suggested a repo to house these scripts](https://github.com/StylishThemes/GitHub-Dark/issues/1002#issuecomment-535816570), the main reason behind is because often to add a new feature to a larger style like GitHub/Stack Overflow/others, its a great deal of work and time, where a override style is a cleaner faster way to handle it.
Because some older styles are a disaster area since they apply styling to global selectors like div/span etc where default stylesheet doesn't, and then its extremely hard to fix issues and removing these global selectors breaks a million and one things. Like in the GitHub style we cant use stylus preprocessor without a serious overall or more convoluted ways to handle certain things. Stack Overflow is one such style I fixed the umpteen issues and reached a point where it would be easier/faster to re-write style properly.

So **TLDR;** we need a simpler way to handle whatever we have time to handle, we are not many active devs on the day to day and we dont just exclusively work on these. The list of issues here grows and people are clearly burnt out.

@xt0rted @silverwind please chip in your 2c =) Im hapy to handle the repo and styles in the repo, but would need help maintaining them.

Also please see **https://github.com/style-it-themes/style-generator/issues/1**

**Comment by the-j0k3r** [comment]
OK thinking of a name for this repo what about: **Auxiliary styles** if so thumbs up this comment so as to gauge support or please make a suggestion.

**Comment by xt0rted** [comment]
How about `GitHub-Dark-Extras`? Or `GitHub-Dark-Features-No-One-But-Me-Wants`?

**Comment by Mottie** [comment]
Added a poll to the first post.

**Comment by xt0rted** [comment]
Turns out you can't switch your vote, instead it just adds a new one 😕

**Comment by the-j0k3r** [comment]
NEWS: https://github.com/StylishThemes/Feature-Override-Styles has been created.

**Comment by the-j0k3r** [comment]
UPDATE: Some styles already populating https://github.com/StylishThemes/Feature-Override-Styles repo. A few more and were done here.

Contributions and help moving remainder of styles welcome.

**Comment by the-j0k3r** [comment]
closing this as solved
