### ISSUE TITLE
`npmhub` compatibility

### ISSUE THREAD

**Issue by fregante** [StylishThemes/GitHub-Dark#1088]
I'd like to improve the look of [npmhub](https://github.com/npmhub/npmhub) with GitHub Dark.

Normally it matches the Files table, for the most part:

<img width="271" alt="files" src="https://user-images.githubusercontent.com/1402241/77597191-5aa91380-6efe-11ea-94e2-9e18c1795340.png">
<img width="352" alt="npmhub" src="https://user-images.githubusercontent.com/1402241/77597193-5bda4080-6efe-11ea-9b93-49f40d0849e3.png">

But it's not a `table`, so it doesn't get your updated style
<img width="609" alt="npmhub dark" src="https://user-images.githubusercontent.com/1402241/77597198-5ed53100-6efe-11ea-8ed7-f51b0362b2d4.png">

This is the CSS for that white border:

https://github.com/npmhub/npmhub/blob/1612065210afcec8df80064567b736f507335dfc/source/content.css#L8

**Comment by the-j0k3r** [comment]
Hello there and thanks for reaching out with the Question.

We dont support this extension at all at this time, I'll see if I can add it to our generator.

**Comment by the-j0k3r** [comment]
Turns out this already exists, https://github.com/StylishThemes/GitHub-Dark/blob/0f8ada418262dff642170988296bfdae4dbddf14/github-dark.css#L9849-L9852

However hpmhub has updated their CSS, so this broke it seems, so its a quick fix.

I dislike how these areas show a blueish border on the `li` sides where all the borders arent blue this comes from a manual rule which needs to exclude this. Should also be fixed.

Theres a minor issue with the header border color vs the file-list border color, but this I'll leave

Please upgrade to 2.0.29

**Comment by fregante** [comment]
Thank you! As the developer of npmhub I was asking you how *I* can use your colors, but thanks for supporting it directly!

**Comment by silverwind** [comment]
I'll integrate this in our generator, which means we'll pull the extension from the Chrome Store and remap the colors. As long as you stick to the same colors GitHub uses, it'll be fine.

**Comment by fregante** [comment]
What if I add it to the boxes themselves?

**Comment by silverwind** [comment]
That'd also work. I just want to avoid extension styles interfering when the extension is disabled.

**Comment by the-j0k3r** [comment]
I tried adding to our gen. But since its one single rule and needs to be overriden with !important I left it and fixed the previous selector.

**Comment by fregante** [comment]
If you have better classes to suggest maybe none of this is necessary. Perhaps I can just make it a (1-column) table and it will automatically get the file table’s style

**Comment by xt0rted** [comment]
If you use `.border-bottom` and/or `.border-top` then it'll use GitHub's default styling which we already handle. An example of a similar layout to this extension is the Dependency Graph page at https://github.com/StylishThemes/GitHub-Dark/network/dependencies.

**Comment by xt0rted** [comment]
After modifying the html to not use a list I was able to get it to look like this.

![image](https://user-images.githubusercontent.com/831974/77655913-7f76a880-6f49-11ea-9b27-c110aad8485b.png)

These are the changes https://github.com/xt0rted/npmhub/commit/459bac0612c437f35db96b785a2db391eebf3285. It could use some more tweaking, but it no longer needs custom css or the modifications to GHD. I'm not sure what it's like with GitLab though.

**Comment by fregante** [comment]
That looks great! Mind opening a PR?

**Comment by xt0rted** [comment]
Sure thing https://github.com/npmhub/npmhub/pull/100.

**Comment by the-j0k3r** [comment]
> I'm not sure what it's like with GitLab though.

Yea that PR heavily uses GitHubs specific classes, I think it would be better if it sourced such CSS separately so a stylesheet for Gitlab or GitHub instead of making it purely Github specific even.

Not sure if these classes will be simply dropped in when using the extension in GitLab only or not though.

**Comment by silverwind** [comment]
Guess we resolved this on both sides now 😉
