### ISSUE TITLE
Black box on network tab

### ISSUE THREAD

**Issue by paz** [StylishThemes/GitHub-Dark#1102]
* **Browser**: Chrome 81.0.4044.122 (Official Build) (64-bit)
* **Operating System**: Windows 10.0.18363 Build 18363 (windows 10 x64 1909)
* **Link to page with the issue**:  https://github.com/JsSucks/BetterDiscordApp/network
* **Screenshot**: https://paz.pw/e3438146ceeade7994eda609ca92c1e6.mp4

**Comment by the-j0k3r** [comment]
Chrome Version 81.0.4044.122 (Official Build) (64-bit)

Link https://github.com/JsSucks/BetterDiscordApp/network

Windows 1809 pro

![generic](https://user-images.githubusercontent.com/31389848/80353283-6aa57180-8875-11ea-99c9-a006d2cbb680.gif)

Cant reproduce.

Id suggest reinstalling Chrome and trying a fresh profile.

**Comment by DE3000** [comment]
I can confirm that I am having the same issue for a while. I have managed to pinpoint it to the `mix-blend-mode:exclusion` CSS style being applied.

Without the mix-blend mode, the black box disappears.

- **Browser**: Opera 68.0.3618.55 (Edition beta) based on Chrome 81.0.4044.113

**Comment by the-j0k3r** [comment]
If that were the case I would be able to repro issue,

**Comment by paz** [comment]
I can confirm @DE3000's findings

**Comment by xt0rted** [comment]
This is the same issue as #395.

I've never had an issue with this page, but looking at it now I'm seeing a black box in chromium based browsers (Chrome, Edge, and Edge dev) but it looks fine in Firefox. Turning off hardware acceleration fixes the issue. A few weeks ago I was looking at this page and didn't have a problem with it, so it's either due to a bug in a recent chrome update or the latest nvidia drivers that were recently installed.

For reference I'm using a GTX1080 founder's edition with version 445.87 of the game ready drivers.

@paz @DE3000 what type of video card are both of you using?

![image](https://user-images.githubusercontent.com/831974/80850855-366edf80-8bec-11ea-8cc8-fca00067e714.png)

**Comment by paz** [comment]
GTX 1060 on 445.87 GR

**Comment by the-j0k3r** [comment]
acceleration is disabled, hence probably why cant reproduce o any chrome based browsers, and I would tend to agree this is a browser issue as with 3d on it breaks this.

**Comment by DE3000** [comment]
I'm using a GTX 980 TI on 445.75, with hardware acceleration on in the browser.

**Comment by silverwind** [comment]
Maybe applying a `-webkit-backface-visibility` or `-webkit-transform: translate3d(0,0,0);` to the canvas might help, those do magic things in Webkit.

**Comment by xt0rted** [comment]
@silverwind so far none of the hacks I've tried have worked. If you rotate the canvas the black box rotates with it.

I've been using a pure black background lately so I've just turned off the `mix-blend-mode`, it matches better like that.

**Comment by DE3000** [comment]
Already tried `-webkit-backface-visibility: hidden;` and `-webkit-transform: translate3d(0,0,0);` with and without prefixes. Does not get rid of the black box.

I ended up using the following:
```css
filter: invert(80%) hue-rotate(135deg) contrast(120%);
mix-blend-mode: unset;
```

**Comment by paz** [comment]
@the-j0k3r issue persists with that commit
@DE3000's solution works but the background is too dark

**Comment by silverwind** [comment]
Reopening, I think we probably should to get rid of `mix-blend-mode`.

**Comment by the-j0k3r** [comment]
>Reopening, I think we probably should to get rid of mix-blend-mode.

Thats what I did i https://github.com/StylishThemes/GitHub-Dark/commit/e70b5198991b052797b047aa347584f346df9df8 but no release has been done

**Comment by DE3000** [comment]
@paz I just adjusted the `invert` percentage to be lower and change the `rotate` so the colours look nicer. Dropping down the `contrast` to 110% "brightens" the background a little.

**Comment by the-j0k3r** [comment]
@DE3000 you probably forgot to remove the old part, see 

https://github.com/StylishThemes/GitHub-Dark/commit/e70b5198991b052797b047aa347584f346df9df8

This removes `div#network.network > div > canvas` from the mix-blend rule and makes a new rule as.

If you didnt remove the  `div#network.network > div > canvas` from the mix-blend-mode then you see the issue still.

```
  div#network.network > div > canvas {
    filter: invert(90%) hue-rotate(180deg) contrast(95%);
  }
```

Which yields

![Screenshot_2020-05-06 StylishThemes GitHub-Dark](https://user-images.githubusercontent.com/31389848/81195914-b4513300-8fbe-11ea-80a2-9e308841ea93.png)

please wait for new release and force update since local edits trump auto updates

**Comment by paz** [comment]
latest update works!
