### ISSUE TITLE
[bug] Code themes do not work on Chrome for general file view

### ISSUE THREAD

**Issue by narfanar** [StylishThemes/GitHub-Dark#1106]
*   **Browser**: Chrome 83.0
*   **Operating System**: Windows 10 build 1909
*   **Link to page with the issue**: Any code page
*   **Screenshot**:  
     

![image](https://user-images.githubusercontent.com/5769148/81877360-1ee90c80-9585-11ea-9fa8-58621b79711b.png)

As you can see, the theme looks like none of the chosen ones.

### Additional context

1.  Installed the userscript on Chrome through TamperMonkey.
2.  None of the three categories (`Github`, `CodeMirror`, `Jupyter`) affect the syntax highlighting of opened files. The extensions seems to work normally otherwise.
3.  Refined GitHub is installed.
    1.  Issue happens with it both enabled and disabled.

**Comment by narfanar** [comment]
Should have been a bug.

**Comment by the-j0k3r** [comment]
Actually no, this isnt a bug, you are using the Github Dark script which is no longer supported.

see https://github.com/StylishThemes/GitHub-Dark-Script

Its been archived because its broken, unsupported.

please use stylus and Github Dark user.css

refer to https://github.com/StylishThemes/GitHub-Dark#installation

Apologies for any inconvenience.
