### ISSUE TITLE
Warning alerts have a blue border now

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1188]
* **Browser**: chrome 84
* **Operating System**: win10
* **Link to page with the issue**: any repo with a security vulnerability
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/87991628-8efb9d80-cab4-11ea-895b-2e1970ec2868.png)

It looks like the colors from the `.flash-warn` class might not be getting generated.

**Comment by xt0rted** [comment]
The default color of these is `rgba(176,136,0,.2)`

**Comment by the-j0k3r** [comment]
most borders are broken since using `$color` because it generates replacement values for color, broder, box shadow etc wherever rhe color is used, problem is that some rules now contain invalid properties based on that, and some rules are OK and some are not.

All the issues I have reported can be traced to that issue.

Short of reverting all @silverwind usage of `$color` which is breaking borders, text colors and other properties, or actually making `$color` way way smarter, you will see a broken beyond anything GHD. 

So far theres no feedback from him despite empirical evidence of the issue.
