### ISSUE TITLE
Hacktoberfest eligibility

### ISSUE THREAD

**Issue by sampi** [StylishThemes/GitHub-Dark#1227]
According to the Hacktoberfest 2020 rules the repository topic `hacktoberfest` has to be added for PRs to be eligible.

Could you add the topic to the repository?

Thanks.

cc @silverwind

**Comment by silverwind** [comment]
I'm not sure we want to add this because this project isn't really that easy to get into and even simple bugfixes can turn out more complicated because of the complexity with the auto-generated rules. I'm happy to flag your PR if that's possible but I don't generally have time or motivation to entertain low-quality PRs.

**Comment by silverwind** [comment]
Recent GitHub changes unfortunately made the build even more complex as it now requires github credentials. Yeah, this project is unfortunately not easy to contribute to.

**Comment by sampi** [comment]
no probs, worth a try =)
