### ISSUE TITLE
Theme request [Neon]

### ISSUE THREAD

**Issue by donno2048** [StylishThemes/GitHub-Dark#1230]
I would love to have a glowing neon effect in GitHub as I have in [Synthwave '84](https://github.com/robb0wen/synthwave-vscode)

**Comment by the-j0k3r** [comment]
The syntax themes are being redesigned in a new format, read the readme at https://github.com/StylishThemes/GitHub-Dark-Syntax-Themes#benefits-of-this-method for information on this.

There's a todo list also https://github.com/StylishThemes/GitHub-Dark-Syntax-Themes#todo.

At this moment everything is stopped, I have no time to dedicate to this much needed side project and adding more incomplete syntax themes in this repo will only make my job harder, so I rather since this is my free time to dedicate to such projects to have the least amount of work possible,

Therefore help wanted and welcome.

**Comment by donno2048** [comment]
Stale
