### ISSUE TITLE
Social preview shows in incorrect size

### ISSUE THREAD

**Issue by fixator10** [StylishThemes/GitHub-Dark#1248]
* **Browser**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.284`
* **Operating System**: `Windows-10-10.0.19041-SP0`
* **Link to page with the issue**: `https://github.com/%user%/%repo%/settings`
* **Screenshot**: ![with the style](https://moeka.is-a-good-waifu.com/4aVgkc3.png)
![without style](https://moeka.is-a-good-waifu.com/2Bow4ER.png)

**Comment by the-j0k3r** [comment]
The problem is because `.js-repository-image-container` is assigned a background color

https://github.com/StylishThemes/GitHub-Dark/blob/3cf9f42aed220d529ea140f9d79ea36b1f51997a/src/main.css#L784

this was added by @silverwind in https://github.com/StylishThemes/GitHub-Dark/commit/ee2eba179bd4655d4084f2268e0aea06bcf81ca5 so Ive no idea if fixing this will break what that was intended to fix.

**Comment by silverwind** [comment]
I don't remember what that selector was for, probably nothing important.

**Comment by the-j0k3r** [comment]
The selector is for the area when thers no image uploaded. Its fixed now both issues.
