### ISSUE TITLE
[Question] How would the ideal userstyles sharing platform be like ?

### ISSUE THREAD

**Issue by KaKi87** [StylishThemes/GitHub-Dark#1267]
### How would the ideal userstyles sharing platform be like ?

1. As a userstyle developer, what would you expect from a userstyles sharing platform ?
2. If this ideal platform would exist, would you publish your userstyles on it ?
3. As a userstyle user, what would you expect from a userstyles sharing platform ?
4. If this ideal platform would exist, would you search userstyles on it ?

### Additional context
https://old.reddit.com/r/userstyles/comments/hqy7w7/stylus_will_have_to_change_its_provider_website/

---

Thanks.

**Comment by the-j0k3r** [comment]
Is this a fact finding mission? Are you planning on developing such site?

**Comment by KaKi87** [comment]
Yes.

**Comment by the-j0k3r** [comment]
There are already projects like that, stylebase.cc and userstyles.world. Also, none wants spyware, or ads or paywalls, and most of all none wants anyone to profit from someone elses work when the person making profit hasnt done anything but collect money.

For the part concerning my styles, I rather not have them in any site, GitHub is fine, if ppl cant find them thats OK too.

**Comment by KaKi87** [comment]
> There are already projects like that, stylebase.cc

I can't seem to find StylishThemes' userstyles on it, and it seems to only work with GitHub repositories, is that something you would expect ?

I did imagined that upload from git (not only GitHub, but every code repository supporting the git protocol) would have been a feature, but not the only way, I would also add direct upload like userstyles.org and greasyfork.org do, and upload from arbitrary URL.

> and userstyles.world

That one seem to require manually filling markdown files and submitting a pull request to a repository, is that something you would expect too ?

I would have thought that a better solution would be to auto-detect the theme's features from the CSS metadata headers like userscripts do.

> None wants spyware, or ads or paywalls, and most of all none wants anyone to profit from someone elses work when the person making profit hasnt done anything but collect money and contribute 0 to the style(s).

Agreed : if I come to create a userstyles sharing platform, it would be FLOSS, ad-free and tracker-free.

> For the part concerning my styles, I rather not have them in any site, GitHub is fine, if ppl cant find them thats OK too.

Can they ?
You'll tell me there are repository tags of course, but there's no standard for their usage, anyone do what they want (`userstyle`, `userstyles`, `usercss`, `example.com`, `example.com-dark`, etc.)
Additionally, you will not only find userstyles, but also userstyles managers, like Stylus, and even userstyles sharing platforms.
So, I'm not sure how GitHub's search engine helps in that matter.
And finally, users are only familiar with Stylus, that's why there is a *Find styles* button on Stulys, they won't understand how a website like GitHub works.

> I would not search for userstyles, This is for users only [...] I dev what styles I use

Understood.

> users are a dime a dozen, what projects need is help [...] 99% of users dont know CSS

I know and I agree, unfortunately, as developers, we can't force users to code, as users, their role is to use and report bugs.

Actually there could be a way to solve that problem, but it is against my principles so I would never implement it, but here it is anyway : it would be possible to create a closed platform using an anti-leeching algorithm, which would measure the ratio of contributions vs downloads for each user, therefore forcing consumers to contribute, for example, at least half as much as they consume.

> projects already exist that work well enough for the purpose

I think there is one other thing missing from the platforms you mentioned : community features. (commenting, reporting bugs, rating, etc.)

> the more sites that exist duplicating same styles, isnt going to be better for userstyles or developers or users. What these sites that exist need is help.

That's also true, that's why I'm trying to get direct feedback from you, developers and users, in order to create the one platform that will truly meet everyone's needs, that's what I need help for.

Thanks

**Comment by the-j0k3r** [comment]
>I can't seem to find StylishThemes' userstyles on it, and it seems to only work with GitHub repositories, is that something you would expect ?

There are plenty styles form various authors inclusing this org, just scroll down, it seems you cant search by authors.

>and it seems to only work with GitHub repositories, is that something you would expect ?

Yes, git is everywhere not just GitHub/GitLab, I wouldn't expect site xyz to decide how my styles are to be shared or supported, even if the license is permissive to allow styles to be hosted elsewhere without my permission.
If you look usercss has metadata that is followed when using Stylus. 

https://github.com/StylishThemes/Wikipedia-Dark/blob/e1050b19f4cff4396712490d12064154474f899f/wikipedia-dark.user.css#L2-L10

I dont expect any site to undo the original devs intentions by in any way trying to change that intention.

>That one seem to require manually filling markdown files and submitting a pull request to a repository, is that something you would expect too ?

Any simple way to submit styles is a welcome process especially if it doesnt require access to site xyz via login.

>So, I'm not sure how GitHub's search engine helps in that matter.
And finally, users are only familiar with Stylus, that's why there is a Find styles button on Stulys, they won't understand how a website like GitHub works.

GitHubs search is not perfect and Stylus is using what it uses for their own reasons, I dont really Care if my styles are found by users or not, I dont dev styles for that purpose.

>I know and I agree, unfortunately, as developers, we can't force users to code, as users, their role is to use and report bugs.

Contributing is not only code, assuming that the only way to contribute to a project is by submitting code, then we are lost before we start. I would expect users to make contributions of any kind that they can make, if it has code or not, its beside the point. This is rather an important point, users should know and be so educated that many ways to contribute besides code.

>I think there is one other thing missing from the platforms you mentioned : community features. (commenting, reporting bugs, rating, etc.)

I think not, sorry, I wouldnt want to find that my styles are now on site xyz (mostly without my knowledge or permission even if license permits) and then that it now offers users a way to ask for support there instead of the repo that is already setup for these purposes.
Users on said sites, like userstyle.org, use comments (or any text they can submit) to report bugs but then the dev is not there to provide any support.

What does that say about  the dev or site? Sorry definetly not, support should point to where style points to.
Of course not all styles are usercss, not all styles use git and not all devs provide, source you can contribute back to, they dont provide any support. Its not a perfect situation but its the reason whey I do rather than use someone elses work that follows some cowboy unrules.

>That's also true, that's why I'm trying to get direct feedback from you, developers and users, in order to create the one platform that will truly meet everyone's needs, that's what I need help for.

I think existing sites are new and need to be developed to accommodate how styles are developed, Ide rather contribute than work on the same but different site, and not just add styles of low quality like userstyles has for the sake of content.. Many devs I know rather do their own then to work on someone elses ideas, I also am very aware that getting code merged is not as simple as it would be if you working for yourself. The opensource spirit is dying slowly of death by ego.

Also, a personal dislike is having to create yet another login or use gmail, github, So any site that demands this will find one less person using it.

All and all, both sites I mentioned are imperfect because they are new and only one dev at the elm. Until they get fed up and then like openusercss disappear without a trace.

**Comment by KaKi87** [comment]
Alright, perhaps I should have mentioned the two primary goal of my project, which are : providing **centralized** access to userstyles, and being **user**-friendly.

That's why I would prefer to mirror host userstyles so they can stay online for users in case the original repository is down for any reason, and that's why I would prefer managing accounts on my own instead of *requiring* an account on another platform, like GitHub for instance, that users doesn't use. But, I did imagined that GitHub SSO would be a key feature.

Although I didn't expected that serving users would not be one of your goals, it is still an interesting point of view.

Thanks for answering. :)

**Comment by the-j0k3r** [comment]
@vednoc @raitaroh thoughts?
