### ISSUE TITLE
Does this work with enterprise github in Safari with cascadea ?

### ISSUE THREAD

**Issue by samipshah** [StylishThemes/GitHub-Dark#1291]

**Comment by the-j0k3r** [comment]
See https://github.com/StylishThemes/GitHub-Dark/issues/1086 and https://github.com/StylishThemes/GitHub-Dark/pull/938

Cascadea is neither here nor there for this since it supports usercss, I dont know how it works with this style if you can configure anything after its installed.

You could have searched for this though.
