### ISSUE TITLE
Text is unreadable as of v4.3.116

### ISSUE THREAD

**Issue by fanninpm** [StylishThemes/GitHub-Dark#1320]
* **Browser**: Firefox 91.0.2 (64-bit)
* **Operating System**: Manjaro Linux x86_64
* **Link to page with the issue**:  here, for example
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/27117322/133014127-1778ae8e-4afd-4508-ac08-9ee3f0b05dd9.png)

**Comment by HexedHero** [comment]
Entire theme is un-usable, wtf did Github do

**Comment by Banderi** [comment]
Still 4.3.114 here, can confirm it's a Github-side fuck-up.

**Comment by NickAcPT** [comment]
By the way, changing the current GitHub theme from `Default light` to `Default dark` alleviates the issue temporarily.

**Comment by Banderi** [comment]
> By the way, changing the current GitHub theme from `Default light` to `Default dark` alleviates the issue temporarily.

Thank you for the suggestion! Definitely a night and day difference.
Personally I'd say the `Dark dimmed` is even closer to the earlier theme.

**Comment by RheingoldRiver** [comment]
For anyone struggling to use github at all right now, here's a link to the preferences page where you can change it: https://github.com/settings/appearance

**Comment by mallowigi** [comment]
They added `!important` to a lot of classes...

**Comment by the-j0k3r** [comment]
> They added `!important` to a lot of classes...

Not quite, they are now using different CSS vars depends on what page you visit, this is one, profile another, none of these are important anything, which is what is broken on screenshot.

the old `bg-white` has been slowly being replaced with `color-bg-primary` which is an Important property, like in notifications and other pages.

Im not a fan of their choices but they do make them no matter what, please do send feedback to GitHub in a constructive positive manner so it doesn't get dismissed. Only then we can have more sensible choices.

Because lets face it, they provide their own internal styles and those dont break so much, except where some developers are using still inline colors without using the vars at all/

This style even though it sports all the modded css vars included the new in use, is in wrong subdomain and other unique weirdness due to the old design + new github CSS vars dont play well with how this style is done via generator.
So this types things will happen more often.
