### ISSUE TITLE
Non-underlined links in issue posts/comments

### ISSUE THREAD

**Issue by webknjaz** [StylishThemes/GitHub-Dark#1321]
It looks like GH changed their CSS to have
```css
a {
    text-decoration: none;
}
```
which effectively means that any links show up as regular text. If you hover on the words of the anchors, they'll become underlined but there's no way to guess if something in the text is a link or not.

* **Browser**: Chrome
* **Operating System**: Gentoo
* **Link to page with the issue**: https://github.com/ansible/ansible-runner/issues/823
* **Screenshot**: N/A

**Comment by Vangelis66** [comment]
... This is yet another manifestation of the considerable blow **Microsoft** dealt to `GitHub Dark` with their GitHub "overhaul" ( 😠 ) of Mon, Sep 13th (see also https://github.com/StylishThemes/GitHub-Dark/issues/1320) ...

However, the title of this issue is somewhat misleading in that, before the massive breakage of 9-13, **live links** with the `GitHub Dark` userstyle would display in blue-coloured characters (still **non-underlined**), as is the case with the GitHub offered "themes" 😉 ; the ill result of the 9-13 changes is that now links don't stand out, without hovering on them, from normal text (as you said), but the fix is not to add underlining to them (as implied by this issue title), but to restore the way things were before (i.e. add different colour to the characters inside the link) ... 😃
