### ISSUE TITLE
Network Graph not showing properly

### ISSUE THREAD

**Issue by NovaRain** [StylishThemes/GitHub-Dark#1339]
It seems GitHub changed the network graph display recently, now with GitHub-Dark the graph is only displayed in an extremely narrow box, making it virtually unusable. If I turn off the style, the box is displayed normally (although I remember the display was taller before) and I can see/drag the graph.

* **Browser**: Firefox 95.0.2/97.0.1
* **Operating System**: Windows 7 x64
* **Link to page with the issue**: all network graphs on GitHub, e.g. https://github.com/StylishThemes/GitHub-Dark/network
* **Screenshot**:
  ![network](https://user-images.githubusercontent.com/8564973/156081692-54872b0f-95f6-4b12-bf4b-b13ba66d7c32.png)

**Comment by silverwind** [comment]
Does not work for me with style disabled either, so I think this is a GitHub bug.

**Comment by neilh10** [comment]
Yup something changed and it looks to be pretty un-useable  though for me its on the standard theme, not changed. 
A shame because its a way of seeing how  forks of open source are being updated.
Under IE 
![image](https://user-images.githubusercontent.com/2766619/156620743-7b90f9a6-9927-4d9c-b3a6-9c68027f7356.png)

Under Chrome 
![image](https://user-images.githubusercontent.com/2766619/156620594-9646e891-31a0-406a-b3ef-be336d1e9c82.png)

**Comment by NovaRain** [comment]
Looks like the network graphs got fixed.

**Comment by neilh10** [comment]
Better for me. Thankyou to whoever fixed it.
