### ISSUE TITLE
How to switch themes within Stylish

### ISSUE THREAD

**Issue by arubdesu** [StylishThemes/GitHub-Dark#211]
Hey, I'm new to all of this (userstyles, etc) but was hoping to use the Solarized Dark theme and can't quite figure it out - I'm starting by having the Stylish Safari Extension enable the GithubDark style, but then I assume I need to edit something in the CSS to use that other theme? Pardon if I'm overlooking a wiki page with the process, but I'm only seeing adapting a new theme sourced from pygments/vim/textmate, I wouldn't even know if there is some sort of local storage of files to make these changes in, so I'm just using the Stylish editor: 
![screen shot 2015-02-15 at 6 58 41 pm](https://cloud.githubusercontent.com/assets/388808/6205704/f8a822ce-b545-11e4-9c1f-14a01348deaa.png)

**Comment by Mottie** [comment]
Hi @arubdesu!

The easiest way to install a style would be to use the [userstyles site](https://userstyles.org/styles/37035/github-dark). Choose your options in the upper right corner, Solarized Dark theme in your case, and click the "Install with Stylish" button.

If you want to use the build script to create your style, follow the [build](https://github.com/StylishThemes/GitHub-Dark/wiki/Build) instructions.

Or, if you want to do things manually, follow the [editing](https://github.com/StylishThemes/GitHub-Dark/wiki/Editing) instructions.

The syntax highlighting themes (the [themes](https://github.com/StylishThemes/GitHub-Dark/wiki/Themes) instruction page about Pygments/Vim/Textmate is no longer in use since GitHub switched from using Pygments. The instructions were left there for posterity, or in case someday they decide to switch back.

**Comment by arubdesu** [comment]
Hey @Mottie, thank you kindly for getting back so quick and all your work on this project! For future generations who think as simply as me, I just went to the [theme I wanted](https://github.com/StylishThemes/GitHub-Dark/blob/master/themes/solarized-dark.min.css), then replaced what is essentially the last line in the css file in the Stylish editor and it seems I didn't screw anything up! I see now the Editing instructions makes reference to it "Lastly, the /*[[syntax-theme]]*/..."
Pardon my oversight, thanks again!
