### ISSUE TITLE
Coloring is off for tabs on organization page

### ISSUE THREAD

**Issue by jawshooah** [StylishThemes/GitHub-Dark#247]
Theme enabled: ![enabled](https://i.imgur.com/2NLdYqT.png)

Theme disabled: ![disabled](https://i.imgur.com/lqdJ0V5.png)

**Comment by Mottie** [comment]
Hi @jawshooah!

Thanks for reporting this problem, I'll have it fixed shortly.

**Comment by Mottie** [comment]
Just so you know, I ended up making the tab transparent. There really is no way to get rid of the bottom border. GitHub was just hiding it by overlapping the white background and since most of us, I think, opt to use a background image, it just wouldn't look as nice with a solid color.

![2015-07-27 15_20_04-stylishthemes](https://cloud.githubusercontent.com/assets/136959/8916741/35356510-3473-11e5-8d72-8eb065af4bf9.png)

**Comment by jawshooah** [comment]
Fine with me. Could the highlight at the top of the tab be a little darker, though? That bright white is a little jarring.

**Comment by Mottie** [comment]
Better? I haven't updated userstyles yet.

**Comment by silverwind** [comment]
@Mottie let's make it `#222` background, we use that style on PR and user page tabs too.

**Comment by silverwind** [comment]
I'll try something

**Comment by Mottie** [comment]
Go for it :grin:

**Comment by silverwind** [comment]
Styles them like other similar tabs, should be easier on the eyes now :yum:

![screen shot 2015-07-27 at 11 05 56 pm](https://cloud.githubusercontent.com/assets/115237/8917716/11ececd6-34b4-11e5-821a-ad9542ba07e2.png)

Also added hover styles and such.

**Comment by jawshooah** [comment]
Looks great, thanks!
