### ISSUE TITLE
GitHub Dark Option Sub-panel

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#271]
Adding ideas for a GitHub Dark userscript

* [ ] Install theme using sub panel.
* [ ] Change background image.
* [ ] Change link colors.
* [ ] Change syntax highlighting separately:
  * [ ] GitHub.
  * [ ] Ace editor.
  * [ ] Jupyter.
* [ ] Change font style & size:
  * [ ] Site.
  * [ ] Code.
* [ ] [Toggle style on & off](https://github.com/StylishThemes/Stylish-Toggle) (but make it work in Firefox).
* [ ] [Toggle wrapping of long code](https://github.com/StylishThemes/GitHub-Dark/issues/253#issuecomment-164019019).
* [ ] Use local storage to save all settings.

**Comment by silverwind** [comment]
I could see a script that fetches the latest style directly from Github, strip `-moz-document`, store it in `localStorage` and apply through adding a `<style id='github-dark'>` on sites that match the regex.

There are some concerns with the above:

 - Checkbox styles will likely not work in Firefox as they require the stylesheet to be applied as user agent sheet. Maybe solveable through some JS wizardry.
- There may be CSS specificity issues because as mentioned above, the style will not be applied as a agent sheet. Possible workaround could be `GM_addStyle`.

The other route is to add just an options panel (reachable through the top right user menu) which toggles certain classes on elements, on which we then can apply rules on in the CSS. Might be a good start to go with this first.

**Comment by Mottie** [comment]
Can a userstyle load files? I don't know if that would work on GitHub with all the restrictions.

I was thinking we could use the script to add a class name to the body to apply the changes, but that would require rewriting the css.

**Comment by silverwind** [comment]
I assume you can't directly load scripts or styles through added tags, as GitHub's CSP would forbid it, but you can use [GM_xmlhttpRequest](http://wiki.greasespot.net/GM_xmlhttpRequest) (which is a unrestricted XHR that works cross-origin) to load a resource and then pop the resulting text into a `script` or `style` tag.

**Comment by silverwind** [comment]
Oh, and let's use jQuery. We might be able to piggyback on the version GitHub loads.

**Comment by silverwind** [comment]
Ressurected the [script](https://github.com/silverwind/GitHub-Dark-Script) and made a basic options panel:

![screen shot 2015-12-13 at 5 32 50 pm](https://cloud.githubusercontent.com/assets/115237/11768001/a6c17912-a1bf-11e5-914d-72bef6089cf3.png)

Still quiet a few things to do like the class toggling functionality. Feel free to contribute.

**Comment by Mottie** [comment]
Moved to https://github.com/StylishThemes/GitHub-Dark-Script/issues/1

**Comment by Mottie** [comment]
Looks like a good start!
