### ISSUE TITLE
Codeblock horizontal scrolling

### ISSUE THREAD

**Issue by keith** [StylishThemes/GitHub-Dark#277]
It seems that GitHub-Dark wraps code in a large code block denoted by three backticks instead of allowing you to scroll horizontally as "normal" GitHub does.

Here's an example:

<img width="766" alt="screen shot 2015-12-31 at 8 57 05" src="https://cloud.githubusercontent.com/assets/283886/12066410/80044512-af9c-11e5-9c3c-7115b9793336.png">

<img width="721" alt="screen shot 2015-12-31 at 8 57 22" src="https://cloud.githubusercontent.com/assets/283886/12066414/87da15f0-af9c-11e5-88cb-c9bb9fd77449.png">

Here's the comment shown in the picture: https://github.com/CocoaPods/CocoaPods/issues/4707#issuecomment-168210747

Is this behavior intended?

**Comment by Mottie** [comment]
Hi @keith!

It actually was intentional. We've been working on a [GitHub Dark Script](https://github.com/StylishThemes/GitHub-Dark-Script) which adds a toggle button allowing you to switch the code wrap, and an option to allow turning it off by adding a "nowrap" class name to the `body`.

I think it might be a better idea to add an option to either add or not add code wrapping so that it can be toggled on userstyles.org as well.

**Comment by keith** [comment]
Awesome, thanks for filling me in!

**Comment by silverwind** [comment]
It looks like more people are prefering non-wrapped code boxes, so I guess we should change it to be non-wrapped by default, and allow a toggle through the script and possibly userstyles.org.

**Comment by Mottie** [comment]
I actually made it code wrap by default. I'll update the GitHub-Dark Script in a bit with a fix, but the option is now available on userstyles.
