### ISSUE TITLE
Collapsed Timeline

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#284]
On `https://github.com/nodejs/node/pull/5020#issuecomment-178095373`, you can see a wavy line that's missing styling. I think we need a replacement image, preferably SVG.

**Comment by Mottie** [comment]
Done :stuck_out_tongue:

**Comment by silverwind** [comment]
Looking good. I suggest reducing the height of the image a bit so it more closely matches the original :)

**Comment by Mottie** [comment]
It only looks taller because it's more pointy... Here they are side-by-side:

![line](https://assets-cdn.github.com/images/modules/pulls/progressive-disclosure-line@2x.png)![line](https://rawgit.com/StylishThemes/GitHub-Dark/master/images/progressive-disclosure-line.svg)![line](https://rawgit.com/StylishThemes/GitHub-Dark/master/images/progressive-disclosure-line.svg)

**Comment by silverwind** [comment]
Might be a Firefox issue, but they look quite different here:

![1](https://cloud.githubusercontent.com/assets/115237/12790247/aaa741a0-caa1-11e5-80a5-e249de228418.png)
![2](https://cloud.githubusercontent.com/assets/115237/12790246/aaa24146-caa1-11e5-82c1-b457d109eb20.png)

**Comment by silverwind** [comment]
Should probably add a `viewBox` to the SVG, I do it for all my SVGs to avoid scaling issues.

**Comment by Mottie** [comment]
@silverwind hmm, I think the issue is the background size setting of `22px 34px`... the original image is 88x34 but the svg is 44x34, so I had to change the original background size from `44px 17px`

**Comment by Mottie** [comment]
Ok, I'll add the view box back.

**Comment by silverwind** [comment]
Yeah, can't test right now, but it should be possible to do without defining background size.

**Comment by silverwind** [comment]
Looks fixed in Firefox, thanks!
