### ISSUE TITLE
Make code wrap the default again?

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#311]
I'm pondering if we should make code boxes and code view wrap by default again, or at least link to [GitHub-code-wrap](https://github.com/StylishThemes/GitHub-code-wrap) from the Readme.

For example, it allows to view all code in minified files like in [this example](https://github.com/silverwind/uppie/blob/master/uppie.min.js). A non-wrapped view on a file like this is pretty pointless, imo.

![](https://cloud.githubusercontent.com/assets/115237/15186882/15baf262-179f-11e6-9425-c167911478b0.png)

**Comment by Mottie** [comment]
I know I originally had it set to wrap as default, but I guess people aren't used to that since it isn't the default behavior (see #277). So, I think we should probably keep it as-is.

But really, I'm up for whatever since I'm using the GitHub-Dark userscript which automatically remembers my desired settings. I can kick back and sip on my margarita.

Oh, I don't know if you noticed, but I split out the code for the three [GitHub-Dark userscript toggles](https://github.com/StylishThemes/GitHub-Dark-Script#toggles). So, even if you're still using Stylish, you can add the code wrap toggle button.

**Comment by silverwind** [comment]
I use above additional style too, so I'm covered as well. I certainly wouldn't want to push my preference on users, but we should of course link to the various additional styles in the Readme.

**Comment by Mottie** [comment]
![agreed](https://cloud.githubusercontent.com/assets/136959/15188647/5cac6c56-176c-11e6-83db-3021f876f189.jpg)
