### ISSUE TITLE
Unstyled content on Organization billing page

### ISSUE THREAD

**Issue by J2TeaM** [StylishThemes/GitHub-Dark#332]
### Unstyled Content

- URL of unstyled content: https://github.com/organizations/[organization]/settings/billing
- CSS Selector: `.billing-per-seat-callout::after`
- Screenshot:

![image](https://cloud.githubusercontent.com/assets/5250117/16239335/930490f4-380e-11e6-9863-8e7adbcd01fa.png)

**Comment by Mottie** [comment]
I updated the userstyles.org site earlier this morning, so since this change is rather minor, it won't get updated there until the next release. If you want to get up-to-the-minute updates, please consider using our [GitHub Dark Script userstyle](https://github.com/StylishThemes/GitHub-Dark-Script).
