### ISSUE TITLE
Flatten button background colors

### ISSUE THREAD

**Issue by poma** [StylishThemes/GitHub-Dark#392]
### Feature Request

Is it just me or buttons with those gradients look really bad on a dark background? I've tried to remove linear-gradients on buttons and already got much better results (in my opinion):
<img width="637" alt="screen shot 2016-08-16 at 02 52 56" src="https://cloud.githubusercontent.com/assets/2109710/17683625/47cc1362-635d-11e6-85f0-1e2c593c0770.png">

Probably it is possible to tweak gradient colors so that they look better (for example shields.io badges with gradients look fine on dark background) but flat buttons looks like a simple and efficient improvement. Maybe make that an option on userstyles.org.

**Comment by silverwind** [comment]
Gradient buttons are the default on GitHub's style, so I ought to keep them that way, at least until GitHub decides to go full-flat:

![](https://cloud.githubusercontent.com/assets/115237/17705240/fd43c0b2-63d7-11e6-8b59-9297333bbf2e.png)

What we could do is to slighly decrease the gradient so the buttons would look a bit "flatter". Note for example that the gradient on green button appears slightly less intense then on grey buttons:

![](https://cloud.githubusercontent.com/assets/115237/17705252/07974c5a-63d8-11e6-8c64-6779b334d662.png)

**Comment by silverwind** [comment]
GitHub uses a `#eee, #ddd` gradient, we have `#444, #333`. I think I'd lean making it a bit darker, maybe `#3f3f3f, #333`.

**Comment by poma** [comment]
Well GitHub's gradient buttons look fine on white background. But if you change the background you need to change gradient colors too to make them look good. Flat is just the easiest way to do that.

**Comment by silverwind** [comment]
Sorry, won't go full flat (yet). After having another look, I noticed GitHub actually has `#fcfcfc, #eee` on the non-hover state, which is a 14 color ticks gradient. We currently do 16 ticks.

Because contrast is easier noticed on dark backgrounds, I think we could go down to 12, maybe 10 ticks. 10 ticks `#202020, #181818` looks like this:

![](https://cloud.githubusercontent.com/assets/115237/17711018/3c67dca2-63f0-11e6-8caf-e0e7d3a584f1.png)

**Comment by poma** [comment]
Much better IMO :+1:

**Comment by un1versal** [comment]
> Because contrast is easier noticed on dark backgrounds, I think we could go down to 12, maybe 10 ticks. 10 ticks #202020, #181818 looks like this:

Yes... that is if your eyesight is 20/20

> Gradient buttons are the default on GitHub's style, so I ought to keep them that way, at least until GitHub decides to go full-flat:

`<rant>`
I will have to **fully** and *passionately* disagree with this stance, you still cant see the downside of this inflexible position when you then introduce weird, ugly and hard to spot differences just because you can spot them and wont move away from GitHub styles that are incompatible with Dark in any decent way.
`</rant>`
