### ISSUE TITLE
Theme request: Monokai - Spacegray Eighties

### ISSUE THREAD

**Issue by torrentails** [StylishThemes/GitHub-Dark#425]
### Unstyled Content

- [x] No other existing issue and/or pull request.

### Feature Request

*Monokai - Spacegray Eighties* theme from Sublime Text.  
The Monokai theme already available is nice, but the background colour is ugly and some of the syntax highlighting isn't quite the same colour and it's bugging me.

https://github.com/pyoio/monokai-spacegray

**Comment by Mottie** [comment]
Hi @torrentails!

We would love to be able to easily add new themes, but GitHub is using "prettylights" as their syntax highlighter, which [hasn't been publicly released](https://github.com/github/pages-gem/issues/160#issuecomment-134186272). It is pretty much impossible to find themes for it.

The themes we have were all hand-crafted to the best of our ability. They aren't perfect, because prettylights wraps code it find relevant a lot differently from other syntax highlighters.

It would help us greatly if you would assist in creating this theme. There are actually three different syntax highlighters on GitHub:

1. **GitHub** (prettylights)

  This GitHub style would need to be hand crafted.

  We do have a [_template.css](https://github.com/StylishThemes/GitHub-Dark/blob/master/themes/github/_template.css) file which can be modified. It contains *relatively* accurate comments for each entry (it's changed several times). 

  Or, use the [github-syntax-theme-generator](https://github.com/primer/github-syntax-theme-generator) created by GitHub. It is set up by defining a [JSON file with color definitions](https://github.com/primer/github-syntax-theme-generator/blob/master/lib/themes/dark.json); but I have yet to get it to work for me.

2. **CodeMirror** (editor)

  A CodeMirror style might be converted from the tmtheme using either of these converters (I have yet to attempt it): https://github.com/codio/tmthemeConverter or https://github.com/dignifiedquire/tmthemeConverter

3. **Pygments** (used by Jupyter pages).

  Converting the tmTheme you share into a pygments style wouldn't be difficult, using the [pygments-from-tmtheme](https://github.com/davinche/pygments-from-tmtheme) script for python listed on [this page](https://github.com/StylishThemes/Syntax-Themes/tree/master/pygments#generators--converters).

As a last resort, each of these styles have a `_template.css` in their respective directories which can be modified if the above methods don't work.

**Comment by torrentails** [comment]
I'll have a look at getting this done myself a bit latter today then.

**Comment by Mottie** [comment]
Thanks again for all your help!

**Comment by torrentails** [comment]
No worries, glad I could help.
