### ISSUE TITLE
[Bug] .text-gray-dark not !important enough

### ISSUE THREAD

**Issue by Bluscream** [StylishThemes/GitHub-Dark#449]
![image](https://cloud.githubusercontent.com/assets/3318223/20856158/dee6059a-b908-11e6-9d10-1f7753716cb6.png)
gets overwritten by
![image](https://cloud.githubusercontent.com/assets/3318223/20856163/ec5cf8f0-b908-11e6-8264-772428167ca6.png)
which results in
![image](https://cloud.githubusercontent.com/assets/3318223/20856166/f89c9f4e-b908-11e6-9186-4a0e0ee59c17.png)

**Comment by silverwind** [comment]
This is a script-specific issue as styles from JS are not really classified as user-styles which can override same-specificity page styles. We somehow need to make sure that our styles (the `.ghd-dark` tag) are added to the end of `<head>` or start of `<body>` so our rules get added later in the chain and win because of that:

<img width="313" src="https://cloud.githubusercontent.com/assets/115237/20857682/180d91be-b934-11e6-9bf2-ac5cea7bbd5a.png">

Weirdly, I don't see the issue in Chrome with Tampermonkey. What browser/userscript engine are you using?

**Comment by Bluscream** [comment]
<details>
-

[![s](http://valid.x86.fr/cache/banner/a1xkj3.png)](http://valid.x86.fr/a1xkj3)

[Settings, Filterlists and Extensions](https://i.imgur.com/Q39NZEn.gif)

Software | Channel | Version | Architecture
--- | --- | --- | ---
[Windows](https://www.microsoft.com/en-us/windows/)  |  Stable | 8.1 (6.3.9600) | x64
[AdGuard](https://adguard.com/) | Beta | 6.1.287.1519 | x86
[Chrome](https://www.google.com/chrome/) | Canary | 56.0.2889.0 | x64
[Opera](http://www.opera.com/) | Developer | 43.0.2423.0 | x64
[Firefox](https://www.mozilla.org/en-US/firefox/products/) | Nightly | 53.0a1 | x64

Last updated: `11/30/2016`
</details>

> Sent from [my Samsung Galaxy Tab 9.3](http://valid.x86.fr/a/4ylsyy).

**Comment by silverwind** [comment]
Can you tell me the order of styles in `<head>` in your inspector? Where's `<style class="ghd-style">` and are there any styles after it? Does it work if you move our style after all other `<style>` tags (Try drag-and-drop)?

**Comment by Bluscream** [comment]
Sadly im on my tablet right now, i will try that when im back on my pc ^^

**Comment by SEAPUNK** [comment]
Hmm, I get the same problem on my side too, from time to time.

**Comment by silverwind** [comment]
I'm pretty sure the issue is because of a possible bug in AdGuard, and only for the script version. If it still persists with the latest version, please open a new issue on https://github.com/StylishThemes/GitHub-Dark-Script.
