### ISSUE TITLE
Glitch With PR Code View

### ISSUE THREAD

**Issue by tzm41** [StylishThemes/GitHub-Dark#488]
- [x] The issue only occurs when the GitHub-Dark style is enabled.
- [x] I am using the most up-to-date GitHub-Dark style!
- [x] No other existing issue and/or pull request was found.
- [x] Please provide steps to reproduce this issue (opening a dialog, etc).

When using this theme the floating bar splits up and the lower part of it moves in the opposite direction of scrolling, as shown in the screenshot.
![screen shot 2017-05-06 at 12 07 44 am](https://cloud.githubusercontent.com/assets/5728283/25769796/c7e87f6a-31f0-11e7-9450-e6d720263d6b.png)

- [x] This issue occurs in the following OS/browser combinations: macOS 10.12.4/Safari Technology Preview Release 29
- [x] Please provide the URL of the unstyled content, if not obvious: private repo.
- [x] If unable to provide a URL, please report the class name of unstyled content: PR page files changed tab.

**Comment by Mottie** [comment]
Hi @tzm41!

Thanks for reporting the problem... I don't own any Apple products so I am unable to test this issue. I'm not seeing it occur in Chrome or Firefox for Windows.

It does appear to be a problem with the `.pr-toolbar.is-stuck:after` definition, which is set with a `position:fixed` style. I'm not sure why it would scroll at all, but since it is occurring in a preview release of Safari, I would guess it's a browser bug.

**Comment by silverwind** [comment]
Yes, certainly a browser bug. I see it in the preview version of Sarfari, but not in the latest release. The background we add to `.pr-toolbar.is-stuck:after` goes floating above the site depending on scroll offset. My attempts to workaround the bug so far have been fruitless.

I wonder if we can find a better way to add the background to this toolbar which does not rely on `position: fixed`.

**Comment by Mottie** [comment]
Please try this change... I re-purposed the shadow div to provide the background instead of using `:after`.

**Comment by silverwind** [comment]
Yeah, that fixed it. Nice work!

**Comment by tzm41** [comment]
Thanks so much for the quick fix!!
