### ISSUE TITLE
font too dark for pl-mh in 3024-night

### ISSUE THREAD

**Issue by franklinyu** [StylishThemes/GitHub-Dark#500]
* **Browser**: Chrome
* **Operating System**: macOS Sierra

The `pl-mh` class of 3024-night theme is too dark, as show in https://github.com/apiaryio/api-blueprint/issues/377#issuecomment-304565604. Can't find the source of this theme, or I'm happy to submit a pull request.

**Comment by Mottie** [comment]
Hi @franklinyu!

The 3024-night theme isn't one of our [supported themes](https://github.com/StylishThemes/GitHub-Dark#available-syntax-highlighting-themes-demo). Our GitHub syntax theme source files are in the [`themes/src/github/`](https://github.com/StylishThemes/GitHub-Dark/tree/master/themes/src/github) folder.

If you would like to provide the theme, it will need to be manually created. This is because the [GitHub syntax theme generators](https://github.com/primer/github-syntax-theme-generator) will still need to be tweaked to match any currently available themes. Check out [their dark theme json file](https://github.com/primer/github-syntax-theme-generator/blob/master/lib/themes/dark.json).

**Comment by franklinyu** [comment]
Sorry I confused GitHub-Dark style with the style in Stylus editor. The related style here is [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark/blob/v1.17.28/themes/src/github/github-dark.css#L66). I think `264ec5` is a little too dark?

**Comment by Mottie** [comment]
Hmm, I just noticed that the [GitHub Dark style](https://github.com/primer/github-syntax-theme-generator/blob/master/lib/themes/dark.json) is actually using `#20272b` as a background color while we have it set to `#141414`. It still doesn't make the `#264ec5` color any more readable.

We use some of the other colors from that style... it appears that `#3c66e2` is a bit more readable. What do you think?

**Comment by franklinyu** [comment]
How about some more red, like `#4c66e2`? Making it less likely to be confused with `.pl-c1`, used in `200 (application/json)` in my example above.

**Comment by Mottie** [comment]
Sure, send us a PR.
