### ISSUE TITLE
Theme Request: Material Theme

### ISSUE THREAD

**Issue by unigazer** [StylishThemes/GitHub-Dark#522]
Edited to show progress:

* [ ] GitHub: **needed** (see #568)
* [x] CodeMirror: Added
* [ ] Jupyter: **needed**

----

Hey, I know I've already asked for one theme from you, `Monokai` and you implemented that the very next day (Thank you on that!).

I was thinking, if there is a possibility, if you could implement this theme for syntax theme:
https://github.com/equinusocio/vsc-material-theme
or something like `One Dark` syntax theme from `Atom`, to at least have `Google Material` colors.

I'm sorry if I'm annoying, it's just that I really like your theme. I mean, my eyes love it, but so do I, too! 😁

**Comment by Mottie** [comment]
Hi @VladimirDev93!

We're all super busy, so if you or someone else finds the time to adapt the material theme to GitHub's PrettyLights highlighter, that'd be awesome!

* [ ] GitHub: **needed**
* [ ] CodeMirror: [Available](https://codemirror.net/demo/theme.html#material).
* [ ] Jupyter: Can be adapted from here: [mkdocs-material](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/extensions/_codehilite.scss).

I can start working on including the CM and Jupyter themes.

**Comment by VladimirDev93** [comment]
Um... I would like to help, it's just I don't know how to help. Any links on what should I do in order to help?

**Comment by Mottie** [comment]
Well, it's a bit complicated... we should have set up a testing platform to make editing & tweaking stylesheets a bit easier.

You can grab one of the template files from the [`src` folder](https://github.com/StylishThemes/GitHub-Dark/tree/master/themes/src) and tweak it to match the theme colors.

Right now, you can test the tweaks for Jupyter & CodeMirror and GitHub diff pages by downloading this repository as a [zip file](https://github.com/StylishThemes/GitHub-Dark/archive/master.zip) and adding the tweaked template(s) to the [index.html](https://github.com/StylishThemes/GitHub-Dark/blob/master/index.html) file to load it and see what it looks like; but because GitHub itself is always changing, you would need to save a copy of [this wiki page](https://github.com/StylishThemes/GitHub-Dark/wiki/Highlighting) and add your tweaked theme to the bottom of the page to test it.

Tweaking the theme is painful. It can look great in one language and awful in another. Luckily, you can add specific language tweaks because the outer wrapper of the syntax block also includes the language, e.g. an HTML block gets a class name of `.highlight-text-html-basic`. 

Again, finding the correct class for a language is painful. You will have to find the actual name that is based on the `tm_scope` attribute from GitHub's [`linguist/languages.yml` file](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml). For example for `php`, you'll see the `tm_scope` set as `text.html.php`... replace the periods (`.`) with dashes (`-`) and add a `.highlight-` prefix. You'll end up with `.highlight-text-html-php` as a specific class name for php syntax highlighted blocks.

My explanation was a bit scattered, but hopefully that gives you a place to start, if you're still up for the challenge.

**Comment by VladimirDev93** [comment]
I'm always eager to learn new things. 

I understood what you've said, so I will give my best to contribute. I will create a repository on my profile, push code there and in the end, I will transfer the ownership to you.

But since I've never did something like this before, I don't know how long will it take. I've asked for the syntax theme, I try to make it.

**Comment by Mottie** [comment]
Oh, I probably gave you the most complex route to contribute...

It might be way easier to use [GitHub-syntax-theme-generator](https://github.com/primer/github-syntax-theme-generator). All you would need to do is modify the [`dark.json` file](https://github.com/primer/github-syntax-theme-generator/blob/master/lib/themes/dark.json) to match a Material theme. You can transfer a style from one of [these Material dark themes](http://tmtheme-editor.herokuapp.com/#!/editor/theme/Material%20Dark) by looking at the "scope name" column and adding it to the same, or similar scope, in the `dark.json` file.

**Comment by VladimirDev93** [comment]
I will look into it.

**Comment by VladimirDev93** [comment]
Just an update.

I've been soooo busy lately. Working on 2 sites (including mine) so I don't know when will I be able to contribute to to this request. It's not that necessary, that was just a suggestion.

But keep it open.

**Comment by the-j0k3r** [comment]
I have it on my GitHub theme, but not the syntax, just GitHub colors
