### ISSUE TITLE
GitHub Blog

### ISSUE THREAD

**Issue by VladimirDev93** [StylishThemes/GitHub-Dark#590]
Have you thought about styling the blog page? https://blog.github.com/
Or can you just add the RegExp link?

**Comment by xt0rted** [comment]
Looks like @Mottie knew you were going to ask about this https://github.com/StylishThemes/GitHub-Dark/commit/01088ae3c66418636d4021a250c4de73843753d0

**Comment by silverwind** [comment]
Seems the site URL recently changed from github.com/blog to blog.github.com. I'll do a minor adjustment on it, then do a new release.

**Comment by Mottie** [comment]
@silverwind I already added it to the regex.

**Comment by silverwind** [comment]
Yeah, I meant some styling fixes. v1.20.24 is out with the blog fix.

**Comment by darkred** [comment]
The URL has changed again, now to github.blog .

**Comment by xt0rted** [comment]
We haven't styled the blog (for now) because there's a lot more content there now and the existing style doesn't really cover it anymore.

They switched from using github pages & primer to wordpress. If we do continue to style this it might be best to move it to its own user style since it's a completely separate site from github.com.

**Comment by silverwind** [comment]
Agree. With the old blog being integrated in the main site, it was effortless to support, but this new site is a whole different beast.
