### ISSUE TITLE
Text too dark with pl-smi, pl-s

### ISSUE THREAD

**Issue by DarkDreth** [StylishThemes/GitHub-Dark#688]
* **Browser**: Chrome
* **Operating System**: Windows
* **Screenshot**:
![image](https://user-images.githubusercontent.com/9059611/42706214-dfde3ebc-868a-11e8-8b22-5b7a8602ccbb.png)

* **HTML of the section where the issue occurs**:

````html
<span class="pl-s"><span class="pl-pds">"</span>fmt<span class="pl-pds">"</span></span>

<span class="pl-smi">Age</span>

<span class="pl-s"><span class="pl-pds">"</span>Gopher<span class="pl-pds">"</span></span>
````
Note: I have no idea how the divs are set up and if there are language specific divs, but these divs seem to be used in Golang as I can't find these issues in other repos I use.

**Comment by Mottie** [comment]
Hi @DarkDreth!

How old is that screenshot? I just went to https://github.com/golang/go/blob/master/src/fmt/export_test.go, and the file has 3 lines (non-comments).

![](https://user-images.githubusercontent.com/136959/42712581-d30802be-86b1-11e8-94e7-3bb710331c2c.png)

Also, which syntax highlighting theme are you using? It almost seems like you're using the raw [github-dark.css](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css) file without installing it through userstyles.org... because the syntax highlighting themes are added based on your selection.

If you're using stylus, you can install [github-dark.user.css](https://github.com/StylishThemes/GitHub-Dark/raw/master/github-dark.user.css) directly from our GitHub repository. And it will include a syntax highlighting theme as expected.

And lastly, if you have a userscript manager installed (Tampermonkey or greasemonkey), you could use our [GitHub-Dark script](https://raw.githubusercontent.com/StylishThemes/GitHub-Dark-Script/master/github-dark-script.user.js).

**Comment by DarkDreth** [comment]
Ahh, that seems to have fixed it. I tried pasting it in as I'm also working on a Corporate github. I guess I could try changing the urls applied to and reinstalling for github. You can mark this closed, thanks for the help!

**Comment by silverwind** [comment]
You should still be able to paste the `github-dark.css` into Stylus and get the Twilight theme applied correctly, and I just verified that this is the case. Mind telling us where exactly you pasted it?

**Comment by DarkDreth** [comment]
I used the CSS snipet from userstyles and pasted it into the code1 block after clicking write style for github.com

![image](https://user-images.githubusercontent.com/9059611/42722749-7c2e3148-8706-11e8-9fba-d7e0628689c8.png)

I believe after that didn't work I tried the github-dark.css in this repo.

**Comment by silverwind** [comment]
Ah yes, that would give you a style without a code theme because these themes are tacked on by the site when you click "Install". Refer to the [README](https://github.com/StylishThemes/GitHub-Dark#installation) for supported installation methods.
