### ISSUE TITLE
tooltiped (over Watch/Unstar/Fork) z-index when logged out

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#695]
Only when logged off, when logged in tooltipped isnt called on hover in this area.

* **Browser**: FF 61.01
* **Operating System**: Linux/Win10pro
* **Screenshot**:

![tooltiped](https://user-images.githubusercontent.com/31389848/42816731-b08c02d4-89c3-11e8-8ca9-dd3918b7aa17.gif)

ref: https://github.com/StylishThemes/GitHub-Dark/commit/af6c3a1fff6725ec7d0c2aae597098bcd9ff2934

**Comment by the-j0k3r** [comment]
Upon some closer look, this issue is present even when GHD is disabled... The Headr z-index is 32 so anythng higher should fix this... right? (rhetorical Q.

**Comment by Mottie** [comment]
Hi @the-j0k3r!

Looks like this should be reported to GitHub.

I'm not sure why there's a z-index on the header when it isn't sticky. The wrapper even has a position relative applied. 

I'm seeing this same issue with our [GitHub fixed header](https://github.com/StylishThemes/GitHub-FixedHeader) style, but I'm not really sure why those buttons need a tooltip when you're logged out since clicking on them will take you to the login screen.

Either way, it's not a rhetorical question since the tooltip has a z-index of `1000000`. It should work, but I think it isn't because of the [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

**Comment by the-j0k3r** [comment]
>Looks like this should be reported to GitHub.

To whom exactly out of curiosity? Via contact, may as well report it to Santa.

I dont think that z-index fixes it, I added something even higher than that and it went nowhere.

Im not even going to try to make sense of whys, waste of time :)

**Comment by Mottie** [comment]
> Via contact, may as well report it to Santa

It's like playing the lottery. You can't complain that you didn't win if you never enter... in other words, if you don't report it, then it'll never get fixed.

**Comment by the-j0k3r** [comment]
I dont play the lottery :)

> in other words, if you don't report it, then it'll never get fixed.

Not my experience, nothing I reported ever got fixed, so Im definitely not wasting my time barking up that tree anymore. Same difference with less user frustration :)

**Comment by the-j0k3r** [comment]
I see, cant blame you, if there were a repo I would try, but via contact Im not.
