### ISSUE TITLE
Revisiting GHD v2

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-Dark#720]
I spent some time working on a new method to generate the GitHub Dark style.

https://github.com/StylishThemes/New-GitHub-Dark/tree/nearest-color

Basically, it uses a very similar method as the "generate" script:

* Load css files directly from GitHub.
* Combine all files.
* Strip out all non color definitions (using [postcss-colors-only](https://github.com/rsanchez/postcss-colors-only)).
* Replace color definitions:
  * Use [perfectionist](https://github.com/ben-eb/perfectionist) to make processing more consistent.
  * Replace all blue color equivalents with our `base-color` - defined in a preset palette file.
  * Then process the remaining colors by first inverting it, applying a hue rotate of 180 and brightening it slightly (using a [Color](https://github.com/Qix-/color) library).
  * Then, using the palette, find the closest color match (using the [nearest color](https://github.com/dtao/nearest-color) library).
  * Replace color definition with a css variable.
* Combine source files, with specific definitions for supported addons, bug fixes, etc., with the extracted style.

The resulting user.css file is about 700 KB! About 300 KB larger than our current GHD style 😿, but it might be a step in the right direction.

Also, right now, it looks really bad... it needs **a lot** of tweaks like getting the green buttons to look green! I think the nearest colors are being matched to grey instead of the actual colors, so the order should be:

* Replace blue with `base-color`.
* Replace all the highlight (non-gray) colors.
* Then, manage the grey colors.

Anyway, I wanted to get some more feedback before I waste any more time on this method... it's huge, which shouldn't matter too much if it's a usercss file. And it needs a lot of tweaking, but in the long run it would save us a lot of work.

Try it out: [GHDv2.user.css](https://raw.githubusercontent.com/StylishThemes/New-GitHub-Dark/nearest-color/github-dark.user.css)

**Comment by silverwind** [comment]
Thanks for picking this up. Some feedback:

- We should put styles targeting different sites into their own `@-moz-document` sections.
- You can drop the `!important` on generated rules. The styles will win because of order.
- You can save some space by merging adjacant rules with the same properties in them.
- You can save some space by merging adjacant rules with the same selectors.
- I'd move user-defined rules to it's own file to keep the us sane.
- The step above requires a build step. Might be worth to move to SCSS with a build step in place. Also, CSS variables look ugly :)

**Comment by silverwind** [comment]
For the space savers, check out https://github.com/StylishThemes/GitHub-Dark/blob/6ad2be739ec0870f9af8800349eb5309c9d9dde1/tools/generate.js#L264. It's reverted now, but this function was working pretty solid there.

**Comment by silverwind** [comment]
Or just use a minifier like `clean-css` on the generated content, it ought to find more size optimizations.

I just had another idea: What if stylus would support `@import` with local caching? We could just import one fat ugly generated blob directly from GitHub and Stylus could cache it until the style is updated. Greasemonkey already does this for require'd JS/CSS code.

**Comment by the-j0k3r** [comment]
I would never use anything that uses @import, just sayin.

**Comment by the-j0k3r** [comment]
> What's so bad about `@import`?

Ive answered that above

 1)  It would be a security issue to allow users to create styles that would potentially import unknown CSS especially usercss, Stylus doesnt have any checks bulit in to warn/block of these potential dangers at this time. openstyles/stylus#385 or other malicious payloads.

2) its cached, probably no user accessible data and not in human readable format.

3) I dont like not knowing what I am adding to my browser under any circumstances,

**Comment by silverwind** [comment]
> security issue

Don't see one. The author is responsible for ensuring the URLs they include are genuine and in the case of GitHub, they're fully in control of the author. CSS password extractions are a joke in my eyes, not practical.

**Comment by silverwind** [comment]
> its cached, probably no user accessible

These parts are usually not meant for users to edit and they can probably override any rule in the with their own one defined later. But I guess Stylus could add a "Show imports" button.

**Comment by the-j0k3r** [comment]
Lets assume all is OK with that and that there are really no security implications and that all authors are great people..

> These parts are usually not meant for users to edit and they can probably override any rule in the with their own one defined later. But I guess Stylus could add a "Show imports" button.

I still like to have things in human readable format, I imaging you want these cached because it will be minified, even if there is nothing in there for users to chnage you can still look and refer to it.

I think like this were just adding layers of complexity needlessly because it would be prettier (thats what it feel like). I like usercss and regular styles because its all right there, its accessible, readable, may get quite large but still all available, readable and more user friendly.

I decided to get into styling because of these, it encouraged some curiosity, Im not sure if I can say the same about that proposal.

**Comment by silverwind** [comment]
One thing we have to account for in the generator is that media-queries are also replicated in the generated CSS, the current script mushes them together with other selectors, which is not really correct.

**Comment by Mottie** [comment]
Interesting article - https://css-tricks.com/switch-font-color-for-different-backgrounds-with-css/

It might be useful somewhere, but it doesn't work in IE/Edge.

**Comment by xt0rted** [comment]
>It might be useful somewhere, but it doesn't work in IE/Edge.

GitHub no longer supports IE as of June I think it is.

Stylus doesn't run on Edge due to missing/broke apis. Greasemonkey does run on Edge but GitHub-Dark doesn't work with it because Edge doesn't ignore CSP headers for injected scripts like the other browsers do.

The only way I was able to get GitHub-Dark running in Edge was to setup a custom extension with the css in it, but since you still can't submit extensions for inclusion in the store it's a moot point.

I don't think it's worth caring about IE or Edge at this point.

**Comment by the-j0k3r** [comment]
> I don't think it's worth caring about IE or Edge at this point.

Ever, I would say. :)

GHD in edge? Wouldnt it be possible with https://github.com/StylishThemes/GitHub-Dark-Script?

**Comment by xt0rted** [comment]
I take back what I said, the CSP header issue was fixed in the most recent version so this does work with Tampermonkey now.

![image](https://user-images.githubusercontent.com/831974/44180651-9695b900-a0cb-11e8-8680-fbca073074ae.png)

The user experience is kind of trash though. The site loads unstyled and then once finished loading the theme is applied 🤢

**Comment by Mottie** [comment]
> Also, CSS variables look ugly :)

@silverwind Here's an argument for using css variables instead of placeholders - https://github.com/StylishThemes/Wikipedia-Dark/issues/49#issuecomment-436829734 - Safari users now have [Cascadea](https://cascadea.app/), so if a user installs our UserCSS, none of the placeholders get modified.

**Comment by silverwind** [comment]
I prefer SCSS-style variables, but I'm happy to use the CSS ones if it allows us to skip the build step, so if you wanna do it, we can do it in the current GHD too.

**Comment by silverwind** [comment]
No sense to keep this open.
