### ISSUE TITLE
Hyperlink color needs more contrast?

### ISSUE THREAD

**Issue by rauchg** [StylishThemes/GitHub-Dark#773]
I wonder if you have considered that perhaps the blue color of the hyperlinks could use some more contrast.

Reddit dark mode:

![image](https://user-images.githubusercontent.com/13041/48669352-8de8c080-eac8-11e8-90fd-c02eb3823b59.png)

GitHub dark:

![image](https://user-images.githubusercontent.com/13041/48669353-904b1a80-eac8-11e8-82a9-53c4899d9ae3.png)

Notice Reddit's stands out more without being necessarily jarring. My 2c!

---

To remove the subjectivity, perhaps we could focus instead on the WAI accessibility guidelines for contrast, and ensure all the color decisions are up to that standard.

Example: https://webaim.org/resources/contrastchecker/

**Comment by Mottie** [comment]
Hi @rauchg!

The link color (aka base color) is customizable.

If you've installed the style from userstyles.org (not recommended since we can't update the style anymore due to a server error), use the [advanced style settings](https://github.com/StylishThemes/GitHub-Dark/wiki/Install#automatic-installation-from-userstylesorg) to adjust the settings.

If you're using [Stylus](https://add0n.com/stylus.html) with the [UserCSS](https://github.com/openstyles/stylus/wiki/UserCSS) version of our style, then open the style settings by clicking on the gear icon in the popup:

![](https://user-images.githubusercontent.com/1310400/34453462-218a589a-ed67-11e7-9040-7d0469eeadc3.png)

If you're using our [GitHub Dark userscript](https://github.com/StylishThemes/GitHub-Dark-Script), then click on your avatar and choose "GitHub Dark Settings", or press <code>g</code> + <code>0</code> shortcut keys ([ref](https://github.com/StylishThemes/GitHub-Dark-Script#main-script)).

**Comment by silverwind** [comment]
Hmm, I think the default being too dark is a valid point. Some testing on the contrast checked. Our `#4183C4`on `#181818` (ratio 4.45) barely fails the requirements for AA contrast (4.5). I could see us increasing this slightly to for example `#4c8ac8` (4.71) or `#4c8ac8` (4.88). AAA requires 7.0, which I think is not realistic.

**Comment by Mottie** [comment]
So the new default will be `#538fca`?

**Comment by silverwind** [comment]
Yes, but lets wait a bit, I think I might go a notch darker after all :)

**Comment by silverwind** [comment]
New base color is `#4f8cc9`, which is a contrast ration of 5.01, or a 12.5% contrast improvement over the previous color. I'll update wiki and userstyles.org.
