### ISSUE TITLE
How to make code deltas easier to read?

### ISSUE THREAD

**Issue by irace** [StylishThemes/GitHub-Dark#808]
Hello – I am using the [Cascadea](https://cascadea.app) for macOS to apply the GitHub Dark [usercss](
https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css), and am finding the code deltas very hard to read:

<img width="1134" alt="screen shot 2018-12-27 at 11 14 52 pm" src="https://user-images.githubusercontent.com/399560/50502529-f7e07800-0a2d-11e9-9415-63ffbc5648bf.png">

In particular, the blue text is hard to read on both the red and green backgrounds.

Am I doing anything wrong? Is there an easy way to change the syntax highlighting to be a bit more legible?

Thanks in advance for your help.

**Comment by the-j0k3r** [comment]
Hi and thanks you for reaching out.
If Cascadea supports usercss, then it stands to reason that it will show the GitHub Dark usercss menu like so.

![usercss](https://user-images.githubusercontent.com/31389848/50508140-dd83ba00-0a80-11e9-9637-55c0e009ceed.gif)
[Github Dark Script ](https://github.com/StylishThemes/GitHub-Dark-Script/blob/master/README.md)

**Comment by silverwind** [comment]
Looks like your style extension does not support usercss option or does not implement them fully. Maybe try the [non-usercss version](https://github.com/StylishThemes/GitHub-Dark/raw/master/github-dark.css).

**Comment by Mottie** [comment]
Hi @irace!

Since Cascadea doesn't currently support the UserCSS format, I think your only option is to create a new style and paste your desired syntax highlighting theme(s) into it. GitHub uses 3 different themes:

* [GitHub](https://github.com/StylishThemes/GitHub-Dark/tree/master/themes/github) for diffs & markdown.
* [CodeMirror](https://github.com/StylishThemes/GitHub-Dark/tree/master/themes/codemirror) used while editing.
* [Jupyter](https://github.com/StylishThemes/GitHub-Dark/tree/master/themes/jupyter) for Jupyter & Help pages.

I'm not sure how to contact the developers of Cascadea to make an enhancement request, but we have a [UserCSS meta parser](https://github.com/openstyles/usercss-meta) & [spec](https://github.com/openstyles/stylus/wiki/UserCSS-authors#usercss-metadata) available.

**Comment by irace** [comment]
Thanks all – using the [non-usercss version](
https://github.com/StylishThemes/GitHub-Dark/raw/master/github-dark.css) that @silverwind linked to seems to have improved things greatly. I’d still rather Cascadea add support for UserCSS, so I'll try following up with the developer.

**Comment by the-j0k3r** [comment]
>  I’d still rather Cascadea add support for UserCSS, so I'll try following up with the developer.

Thats good to hear, fingers crossed on usercss front. I also looked at his privacy policy and looks simple similar to Stylus, however there's no code available to audit. Sure would make things more transparent if it were. :) Good luck and happy to see silverwinds solution worked for you.

**Comment by mikefreuden** [comment]
Hi there! I'm the developer of Cascadea. Just wanted to update you all on this particular issue. I just pushed Cascadea 1.3 to the App Store, which should correctly parse and apply UserCSS variables so that the UserCSS version of this style looks correct. Previous releases didn't really handle UserCSS variables at all, so any properties that depend on variables just, well, didn't work. Now the default values should be applied. (I'm actually using Github Dark in Cascadea 1.3 as I type this!)

I'm still working on implementing UI for actually customizing variables, which should hopefully be in the next release.

**Comment by the-j0k3r** [comment]
@mikefreuden 

Ive updated our wiki page related to [Cascadea](https://github.com/StylishThemes/GitHub-Dark/wiki/Install#cascadea) to reflect this information so if there are any new advances or more up-to-date info feel free to let us know.

=)

**Comment by mikefreuden** [comment]
One (hopefully last) update for you all. Cascadea 1.4 adds UI for customizing `@advanced` and `@var` UserCSS variables, so using Cascadea should now provide a first-class GitHub Dark experience. :)

<img width="462" alt="Screen Shot 2019-06-11 at 9 08 26 AM" src="https://user-images.githubusercontent.com/48981944/59310102-eea93780-8c6a-11e9-8d0d-69c3c22a9c4f.png">

**Comment by silverwind** [comment]
Thanks. Readme [updated](https://github.com/StylishThemes/GitHub-Dark/commit/075761b11cd8aea86c3a25cb638bafe3b15392ca).

**Comment by the-j0k3r** [comment]
Ive updated the wiki page =) Will also give it a whirl in my text macOS vm
