### ISSUE TITLE
PR review status tooltip displays underneath header bar

### ISSUE THREAD

**Issue by tullo-x86** [StylishThemes/GitHub-Dark#841]
* **Browser**: Firefox 64.0.2
* **Operating System**: Windows 10 x64
* **Screenshot of actual behaviour** (all user styles except GitHub Dark disabled):
![image](https://user-images.githubusercontent.com/2888110/51698967-3f2c3b00-1fd1-11e9-81ac-383d77a1f037.png)
* **Screenshot of expected behaviour** (all user styles disabled):
![image](https://user-images.githubusercontent.com/2888110/51698989-46534900-1fd1-11e9-82b6-fff2932373f9.png)

* **HTML of the section where the issue occurs**:

````html
<p>
          
<span class="js-hovercard-left" data-hovercard-type="user" data-hovercard-url="/hovercards?user_id=2888110" data-assignee-name="tullo-x86">
  <a class="no-underline" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="/tullo-x86" aria-describedby="hovercard-aria-description">
    <img class="avatar" src="https://avatars0.githubusercontent.com/u/2888110?s=40&amp;v=4" alt="@tullo-x86" width="20" height="20">
</a>  <a class="assignee link-gray-dark" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="/tullo-x86" aria-describedby="hovercard-aria-description">
    <span class="css-truncate-target">tullo-x86</span>
</a></span>


          <a href="/civicsource/civicsource/pull/2419/files/9968659a60b4fc7e5cbacc286e3d520d031b6983">
            <span class="reviewers-status-icon tooltipped tooltipped-nw float-right d-block text-center" aria-label="tullo-x86 left review comments">
              <svg class="octicon octicon-comment text-gray" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M14 1H2c-.55 0-1 .45-1 1v8c0 .55.45 1 1 1h2v3.5L7.5 11H14c.55 0 1-.45 1-1V2c0-.55-.45-1-1-1zm0 9H7l-2 2v-2H2V2h12v8z"></path></svg>
            </span>
          </a>

        </p>
````

**Comment by the-j0k3r** [comment]
Thank you for your report. =) Seems like some z-index gone awry. Will have a look later if no one gets to it in the meanwhile.

**Comment by the-j0k3r** [comment]
Well I found the issue, and Ive not idea how to fix so far.

This is the tooltips code https://github.com/StylishThemes/GitHub-Dark/blob/6151c049231b9f42ea37df2094cf629bdf1ec26c/github-dark.css#L2040-L2054

Ive tried adding a `z-index: 100001 !important;` GH default for ` .tooltipped:after` is `z-index: 100000` but no dice.

Then I removed this https://github.com/StylishThemes/GitHub-Dark/blob/6151c049231b9f42ea37df2094cf629bdf1ec26c/github-dark.css#L1744-L1757 then this issue is fixed.
I also tried adding a lower z-index value, but that doesnt seem to work at all.

Ive no idea about the issue that is supposed to fix.

@Mottie  for thoughts.

**Comment by Mottie** [comment]
Hmm, yeah it's because we set the `.discussion-sidebar` to `sticky`. It has to do with [the stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). So maybe it's best to remove it since the sidebar is no longer sticky, even in Firefox. What do you think @silverwind?

**Comment by silverwind** [comment]
I still find the sticky sidebar very useful, it saves me a lot of scrolling time. I'd rather get rid of the fixed header, it just takes up screen space for no practical reason (I can already see the issue title in the browser tab and the PR number in to URL).

**Comment by silverwind** [comment]
Could move the sticky sidebar to a addon style I guess.

**Comment by the-j0k3r** [comment]
> Could move the sticky sidebar to a addon style I guess.

to https://github.com/StylishThemes/GitHub-FixedHeader/blob/master/github-fixed-header.user.css?

Someone who uses that and is familiar with it, would best be suited to that transfer. Unless you want a whole new style just for this.

**Comment by silverwind** [comment]
Extracted [GitHub Sticky Sidebar](https://github.com/StylishThemes/GitHub-Sticky-Sidebar) and removed it from here.
