### ISSUE TITLE
Issue box is not styled properly

### ISSUE THREAD

**Issue by anas-qa** [StylishThemes/GitHub-Dark#848]
* **Browser**:
Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* **Operating System**:
MacOS Mojave 10.14.3 (18D42)

* **Step to reproduce**:
1- Dark theme enabled
2- Create new issue
3- Modify the write tab (write any text inside the issue body)
4- Click on "Preview"
5- Disable dark theme
6- Switch back from "Preview" to "Write"

* **Screenshot**:
<img width="1513" alt="screen shot 2019-02-12 at 4 18 41 pm" src="https://user-images.githubusercontent.com/16471809/52635073-4e245000-2ee2-11e9-8e33-a085702f5523.png">

**Comment by Mottie** [comment]
Hi @anas-qa!

I can't reproduce this issue on Chrome 72.0.3626.96 (Official Build) (64-bit) on Windows 10.

Are you using any extensions or userscripts that modify the issue because I can't tell if the red 1 in the bottom right was added to the screenshot or to the textarea?

Either way, this issue might be related to the style manager and not the style itself. I'm using Stylus v1.5.2 and I'm not able to duplicate the problem.

**Comment by anas-qa** [comment]
Hi @Mottie 

No extensions or anything.

It's reproducible through the mentioned STRs on Mac, however, I don't have any nearby Windows OS to confirm you if MAC issue or not.

And btw,
The "red 1" is just a warning hint by [Grammarly](https://app.grammarly.com)

**Comment by Mottie** [comment]
Yep, it's Grammarly that's doing it. It copies the style of the textarea while it's active, so that's why the style persists after turning our style off.

**Comment by Mottie** [comment]
@the-j0k3r It's not exclusive to MacOS, I duplicated the issue using the extension in Windows.

**Comment by silverwind** [comment]
No sense in keeping this open, this is a Grammarly bug.
