### ISSUE TITLE
Improve wording on font-size in usercss GUI

### ISSUE THREAD

**Issue by saildata** [StylishThemes/GitHub-Dark#863]
There is an input for font-size in the usercss GUI, but the code does not include a CSS unit, which disables it if you put something like 14 in without a unit.

Doesn't work: `14`
Works: `14px`

I wanted to mention it in case someone else came across the same issue.

**Comment by the-j0k3r** [comment]
Hello and thank you for your report.

For reference the font size was added in https://github.com/StylishThemes/GitHub-Dark/commit/6e8a11fe2b7045dcbc6d604fecf0d5e36fe580d0

Theres a few solutions I can see here.

1) * We could add some thing in label that indicates user to add units next to value, So selecting one or two to wack in label like (Font size: (add value in px or em etc.)

The issue I see with this personally is heres a large list of valid units which could be used, see https://www.w3schools.com/CSSref/css_units.asp,  would probably give some users the idea theres some restriction to use only certain units like `px` or `em` when in fact all valid ones are OK + space is at a premium in this menu to add more info to labels (because they may wrap also depending on length.)

2) * We could also use the placeholder word `default` to indicate units must be used... e.g. `default (add value + units)`.

3) *  A mix in between 1, and 2.

4) * **My preferred solution** (add some documentation in Wiki about it) and be done. (some volunteer please for this to come forward would be extra nice) =)

@LordJZ to weigh in on this matter since he added the feature.

**Comment by the-j0k3r** [comment]
@silverwind @xt0rted @Mottie for feedback pls.

**Comment by Mottie** [comment]
1. Adding more text would wrap around to the next line, so we could add `Code Font Size (e.g. '10px')`.
2. Since `default` isn't a valid font size, we could completely replace it with text like `(e.g. 10px)`.
3. Bah.
4. Who read instructions? I need a t-shirt that says `!RTFM` on it.

**Comment by the-j0k3r** [comment]
I didnt like the idea of specifying any units because some ppl may think thats all it accepts.

Im partial to the 2, sort of thing. and bah for 3 and 4.

**Comment by Mottie** [comment]
It's an example. We can update the wiki explaining it in more detail. If they know about units other than `px` they may try even without RTFM.

**Comment by the-j0k3r** [comment]
>  If they know about units other than `px` they may try even without RTFM.

If ifs and buts were candy and nuts, we would all have a merry xmas, so the saying goes.

I agree, Ill have a go tomorrow at the label changes, idk about wiki, if anyone volunteers to start it Ill contribute happily.

**Comment by saildata** [comment]
If I thought that everyone (such as my students) would RTM then I wouldn't have filed the issue..

**Comment by the-j0k3r** [comment]
All there is left to do is some wiki entry which Im leaving to some volunteer + info is already in a comment above, if my solution isnt good enough, may the universe have mercy on the students.

**Comment by saildata** [comment]
Awesome, thank you! @the-j0k3r
