### ISSUE TITLE
Selected repo tab has solid color

### ISSUE THREAD

**Issue by bfred-it** [StylishThemes/GitHub-Dark#894]
The tab should match its content color:

<img width="353" alt="" src="https://user-images.githubusercontent.com/1402241/54876430-d6cfcd80-4e4a-11e9-8988-8e88e0591005.png">

But in this case the tab has a solid gray color, while the content is textured:

<img width="358" alt="" src="https://user-images.githubusercontent.com/1402241/54876424-a9831f80-4e4a-11e9-9b39-e6582e256773.png">

* **Browser**: Firefox 65
* **Operating System**: macOS 10.14
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/issues

**Comment by xt0rted** [comment]
The styling for this was moved to [its own user style](https://github.com/StylishThemes/GitHub-Selected-Tab-Color). There's actually a number of GitHub related user styles that you can choose from at https://github.com/StylishThemes/GitHub-Dark#additional-userstyles.

**Comment by bfred-it** [comment]
Why would it be in a separate style? That looks broken *as a default*

**Comment by xt0rted** [comment]
I'm not sure, it's been like this ever since I started using the style. Maybe @Mottie or @silverwind could shed some light on this one?

**Comment by the-j0k3r** [comment]
It looks awful with a bg, cause it doesnt line up.

![Capture](https://user-images.githubusercontent.com/31389848/54899670-e09c1400-4ed0-11e9-9ccd-944768187ae7.PNG)

You can tweak the CSS a little like
```
.reponav .selected.reponav-item {
    background-color: #222 !important;
    background-image: /*[[bg-choice]]*/ !important;
    background-attachment: /*[[bg-attachment]]*/ !important;
    background-position: center !important;
}
```

But that still doesnt look right.

**Comment by bfred-it** [comment]
A `background: none` works:

<img width="356" alt="" src="https://user-images.githubusercontent.com/1402241/54900925-f1b84580-4f0f-11e9-96d7-ed99994f4438.png">

It would be nice to also drop the faint bottom border, but it doesn't look terrible.

**Comment by the-j0k3r** [comment]
Fixed in next release. =) also had to update GHSTC style so the top border color can be overridden.

**Comment by Mottie** [comment]
We ended up removing the border because the orange was so bright & distracting. When we changed it to use the base color, we started adding that same color to all the tabs which made GHD feel too opinionated, so we moved it to a separate style. I think we just forgot to restore the border color afterwards.

**Comment by xt0rted** [comment]
I don't use the background image anymore so this doesn't bother me, but for anyone that does the tab style is inconsistent now.

![image](https://user-images.githubusercontent.com/831974/54936486-f291ad00-4ef8-11e9-9042-005f307af068.png)

**Comment by silverwind** [comment]
I don't see tabs having a opaque background as a bug. They need some background to not look strange on textured backgrounds and `#222` happens to be the most fitting color on our default background.

Will probably have to tweak this later. @the-j0k3r please give such potentially controversial issues a bit more time to discuss before doing changes.

**Comment by silverwind** [comment]
Few changes pushed in https://github.com/StylishThemes/GitHub-Dark/commit/9430d74c6ae1d664d8c9226d1be90b726ffe3c50, partially reverting the tab here and doing some improvements while I was at it. Tabs are now always same height. Results:

<img width="631" alt="Screenshot 2019-03-25 at 23 24 33" src="https://user-images.githubusercontent.com/115237/54958223-58138700-4f55-11e9-9bbc-0ea4763d8f69.png">
<img width="577" alt="Screenshot 2019-03-25 at 23 24 22" src="https://user-images.githubusercontent.com/115237/54958224-58138700-4f55-11e9-877b-c85e4f84eff9.png">

**Comment by the-j0k3r** [comment]
This issue was already fixed along with #895 and removed in https://github.com/StylishThemes/GitHub-Dark/commit/9430d74c6ae1d664d8c9226d1be90b726ffe3c50 I added in https://github.com/StylishThemes/GitHub-Dark/commit/2b1705584f6e81ea099ef0f07512f00470f2c725

Now, since that was done, what are we doing to solve this and the tab background in PRs too?

**Comment by the-j0k3r** [comment]
>  @the-j0k3r please give such potentially controversial issues a bit more time to discuss before doing changes.

Speaking of controversy (because its stiks out in issue report) Why are we purposefully removing the 3px border that exists in GH default on the top tab row? Is it so it looks the same look to all tabs in GHD by default?

As for this issue, I happen not to have strong feelings either way, if it looks better as it is, then @bfred-it will have to use extra css style to fix the quirks he reported.

**Comment by silverwind** [comment]
The tab change is opiniated but well worth it in my opinion. I prefer the plain tabs and its actually more consistent with other tabs on the site too.

There should be no workarounds necessary with the latest change, the tabs have the same dimensions and position like the original ones.
