### ISSUE TITLE
Some marketplace tags have double borders

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#907]
* **Browser**: chrome 73
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/marketplace/renovate
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/55677792-2e931d80-58bc-11e9-9747-ebffe9ac1290.png)

By default these tags don't have a border while our style does, so on the ones that do have a border (Github is doing it with a `box-shadow` for some reason) it's being added twice.

If we adjusted these to use `box-shadow` instead of `border` that might get rid of the issue since the outline variant would override the default style instead of being added on top of it.

**Comment by the-j0k3r** [comment]
I added the outline to generator a while back https://github.com/StylishThemes/GitHub-Dark/commit/cae86ae83fae5d423e757d58164e07d2b904d19a the border already pre-existed.

The problem is that ALL our tags have had borders for the longest time, though doesnt exist like you say in default.

If were replacing the border by a box shadow manually on the tags then thats probably gonna work, else we could also remove the border on these tags in the `.topic-tag-outline`. 2 possible fixes.

We could not have borders in our tags also, but they would lack definition, so while opinionated change I would actually like something like that to stay.

**Comment by the-j0k3r** [comment]
Well, I managed to fix this using box-shadow for topic-tag instead of the border rule, howevr the autogenerated will have to be manually done, else the highlighting done by that rule is no more.

It works well anyway and its better than having borders behind box-shadows. Hope you guys like it. Incoming in 10, 9, 8...
