### ISSUE TITLE
Alternating table row background colors

### ISSUE THREAD

**Issue by stonecrusher** [StylishThemes/GitHub-Dark#939]
Alternating table colors are almost invisible, at first I thought they weren't even considered at all.   Especially if you turn down your monitor brightness at night.
I'd suggest a color **at least** as bright as `#1c1c1c` to see the helpful effect.

Actually there is an autogenerated rule which fits nicely (`#202020`) but is overwritten later by `#181818`.

I changed the whole rule from line 3782 and it didn't look unpleasant (change to color red to see what's affected).

### Before
![2019-05-02_12-23-34](https://user-images.githubusercontent.com/1388389/57069673-94b16b80-6cd5-11e9-8569-2a70c86e14e0.png)

### After
![2019-05-02_12-24-20](https://user-images.githubusercontent.com/1388389/57069687-9ed36a00-6cd5-11e9-9417-ed90089b18bf.png)

### Proposal
![2019-05-02_12-30-07](https://user-images.githubusercontent.com/1388389/57069997-6d0ed300-6cd6-11e9-8ddf-becf6c1834e9.png)

### Info
GHD 1.21.46

Example Link
https://github.com/openstyles/stylus/wiki/Stylish-alternatives#css-injectors

Selector
`.markdown-body table tr:nth-child(2n)`

**Comment by the-j0k3r** [comment]
Hi there @stonecrusher thanks for this issue report.

I agree that the difference between odd/even is a little too nuanced, what I notice mostly is the the default GH vs default GHD is the wrong order e.g. the first row is darker instead of lighter.

But to your issue, I dont think we need to go that light to have more contrast.

Ill have a look and see whats going on in order to try fix both issues if no one gets to it first.

Thanks again =)

**Comment by the-j0k3r** [comment]
OK, taking your suggestion, and addressing order + contrast, what about this?

![generic](https://user-images.githubusercontent.com/31389848/57071492-ea3c4700-6cda-11e9-9585-530014e8b021.gif)

**Comment by stonecrusher** [comment]
Looks definitely better!
Btw what I used in the proposal picture was not `#1c1c1c` but the auto-generated `#202020`.

**Comment by the-j0k3r** [comment]
Was a bit too bright I thought so went with your suggestion instead. The autogenerated is overriden anywho.
