### ISSUE TITLE
Remove grunt

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/GitHub-Dark#945]
I think it's time to drop Grunt and replace it with Node.js scripts. I'm thinking about dropping support for generating a style based on a config file, I guess nobody is really using that anyways. Development tasks will move to npm scripts that just call the node scripts.

**Comment by xt0rted** [comment]
Not sure how useful this will be here but I've been using [npm-run-all](https://github.com/mysticatea/npm-run-all) for my npm scripts and it's been working out pretty well.

**Comment by the-j0k3r** [comment]
@Mottie as already expressed several times his yearning to remove grunt, I agree and would help chnaging diapers if it help this go faster =)

**Comment by silverwind** [comment]
Date bumping outsourced to `ver` in https://github.com/StylishThemes/GitHub-Dark/commit/bf6fd087c60b3dc22b71b42b2ea2dbfbf9004af3, getting there slowly. 😉

**Comment by the-j0k3r** [comment]
Related grunt removal in /StackOverflow-Dark https://github.com/StylishThemes/StackOverflow-Dark/commit/d1ceeec38921d7f6378b5151e11cee3d62276197 and adjusted in https://github.com/StylishThemes/StackOverflow-Dark/commit/2839641d1d5a9ffad5909c8fae3c89d0212c6443

**Comment by Mottie** [comment]
Oh fun. I just discovered that [perfectionist](https://github.com/ben-eb/perfectionist) has been archived. I don't know if there's an alternative.

**Comment by the-j0k3r** [comment]
Well, that project last anything was 3 years ago.

Ive been trying to setup stylelint to use `--fix` to try and do similar since especially cant make perfectionist work as I want in my own themes.

**Comment by silverwind** [comment]
`perfectionist` has a few bugs, but mostly still works for our use case. I'm sure there may be alternatives if one starts looking long enough :wink:

**Comment by xt0rted** [comment]
The modern alternative would be [Prettier](https://prettier.io/). It has Stylelint integration so [you can use both together](https://github.com/hugomrdias/prettier-stylelint). I wasn't able to get them working together, but they claim it works 🙃

**Comment by the-j0k3r** [comment]
Personally I understand any reservations anyone may have while perfectionist still works for our needs,.

Since perfectionist is now unmaintained (and I dislike unmaintained projects that I cant contribute to but depend on) and while the extra workload for someone able to replace it with any working alternative more easily than a total noob like myself, is not to be a motivator when perfectionist still works, I may try to figure it out in the case of prettier-stylelint depending on how easy their docs are easy to follow, of course.

I see they link stylint with the `--fix` option which I already started playing with success in https://github.com/StylishThemes/Pocket-Dark/commit/24d4c6ad4253b706f44c80bb512a394e375756a3 and in my own themes in https://github.com/style-it-themes/appveyor-ci-inspired-dark/commit/cf8c0ac8bdf6d8fc29e5e00b69db923708ee6a0e **which incidentally perfectionist cant handle out of the box** for some/most of those fixes.

Ive integrated my modified [`.stylelintrc`](https://github.com/style-it-themes/appveyor-ci-inspired-dark/blob/5586b47746918bbe00ccfd9d0fb4421aa1035429/.stylelintrc) into the clean script like so.

```json
  "scripts": {
    "clean": "npm run perfectionist && node tools/fix-perfectionist.js && npm run lint",
    "eslint": "eslint --quiet --color tools/*.js",
    "lint": "npm run eslint && npm run stylelint",
    "patch": "npx ver -p patch *.user.css",
    "minor": "npx ver -p minor *.user.css",
    "major": "npx ver -p major *.user.css",
    "perfectionist": "npx perfectionist appveyor-ci-inspired-dark.user.css appveyor-ci-inspired-dark.user.css --indentSize 2 --maxAtRuleLength 250",
    "stylelint": "npx stylelint --quiet --color --fix -- appveyor-ci-inspired-dark.user.css",
    "test": "npm run eslint && npm run stylelint",
    "update": "npx updates -cu && npm install"
}
```

**Comment by the-j0k3r** [comment]
Im slightly curious about performance after reading https://deliciousbrains.com/npm-build-script/

**Comment by the-j0k3r** [comment]
See https://github.com/StylishThemes/GitHub-Dark/pull/1015
