### ISSUE TITLE
Codecov badges are inverted

### ISSUE THREAD

**Issue by auscompgeek** [StylishThemes/GitHub-Dark#955]
Here is a Codecov badge: ![](https://codecov.io/gh/python/cpython/branch/master/graph/badge.svg)

As you can see, it is erroneously inverted.

This one was taken from https://github.com/python/cpython.

**Comment by the-j0k3r** [comment]
Hi @auscompgeek  =) thanks for reporting this issue.

The issue comes from:
https://github.com/StylishThemes/GitHub-Dark/blob/9778fff5dfac0527e28fc6470bc480da386dc31b/github-dark.css#L5800-L5803

This patch was added in https://github.com/StylishThemes/GitHub-Dark/commit/12abc6d0e863ee6a64b0a47ce701e9dc21172100 and tweaked in https://github.com/StylishThemes/GitHub-Dark/commit/9fdf55e9cf24e49f1642e8ae0f5cb52aac6fed48

Im testing a fix adding `:not([data-canonical-src*="badge.svg"]) ` to that selector and, just need to test in other codecov badges in other repos to ensure this covers all instances. Its a weird solution, though it seems to work so far ;).

For reference that line above inverts the first image in [this comment](https://github.com/go-gitea/gitea/pull/6969#issuecomment-493150380)

**Comment by auscompgeek** [comment]
I'm under the assumption that @silverwind just wanted to target those graphs.

If you need other tree diff graphs to look at, you can take a look through https://github.com/thedropbears/pydeepspace/pulls.

**Comment by the-j0k3r** [comment]
Thanks. I think Ill go with the updated fix: 

```css
  img[data-canonical-src^="https://codecov.io"][alt="Impacted file tree graph"] {
    filter: invert(92%) hue-rotate(180deg) saturate(250%) !important;
  }
```
> If you need other tree diff graphs to look at, you can take a look through https://github.com/thedropbears/pydeepspace/pulls.

Thanks again, I looked ta those graphs and they display OK with that fix and badge isnt inverted. Except for me Firefox decided to make some weird render of that graph in https://github.com/go-gitea/gitea/pull/6969#issuecomment-493150380 comment which is really weird.

![generic](https://user-images.githubusercontent.com/31389848/59595778-bab09500-90f6-11e9-85c9-0cd19d857a2e.gif)

expect fix in a few, maybe @xt0rted or @silverwind have some idea why the oddness in one comment and not others. (all styles disabled)

**Comment by silverwind** [comment]
Yes, these were only targeting the graphs.

No idea about your render, maybe update your GPU drivers 😉
