### ISSUE TITLE
Zenhub issue modals not styled on GitHub Enterprise

### ISSUE THREAD

**Issue by Mumumurilo** [StylishThemes/GitHub-Dark#958]
As addressed [here](https://github.com/StylishThemes/GitHub-Dark/issues/407) before.
The Zenhub issue modals are not styled as expected on GitHub Enterprise.

* **Browser**: Firefox 67.0.2 (64-bits)
* **Operating System**: macOS Mojave (10.14.5)
* **Link to page with the issue**: I'm not able to share, it's a GitHub Enterprise page and it's not public
* **Screenshots**:

Example:

<img width="1280" alt="Screen Shot 2019-06-19 at 17 47 08" src="https://user-images.githubusercontent.com/8595653/59799223-4888ad80-92ba-11e9-80c8-ab67f628d98a.png">

Seems like only the `timeline-comment-group` div and its children are appending the style.

![image](https://user-images.githubusercontent.com/8595653/59798849-73263680-92b9-11e9-9dda-49a9ab1eb6ac.png)

By tweaking with the style on the developer view I was able to find an `!important` tag appended to a background parameter on the `partial-discussion-header div`. However, I couldn't find what is making the rest of the modal still have the white background.

![image](https://user-images.githubusercontent.com/8595653/59798870-7a4d4480-92b9-11e9-85eb-59f5b4871a7e.png)

**Comment by silverwind** [comment]
I'm unable to reproduce in github.com:

<img width="1110" alt="Screenshot 2019-06-21 at 23 16 22" src="https://user-images.githubusercontent.com/115237/59951922-bb408700-947a-11e9-968c-4c1c29318390.png">

Nevertheless, did a few tweaks related to loading placeholders.

I'm sorry but if this is still not working for you, you need should probably create a fixup userstyle yourself targeting that enterprise site.

Generally, working with ZenHub is a huge displeasure for me as it slows my browser to a crawl, honestly, I don't plan on doing any more fixes for it because of that.
