### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by MGaetan89** [StylishThemes/GitHub-Dark#966]
"Draft" and "Pre-release" tags use two different colors for the text and the border.

* **Browser**: Google Chrome 75.0.3770.100
* **Operating System**: Ubuntu 18.04.2
* **Screenshot**:
![Pre-release](https://user-images.githubusercontent.com/1009664/61470017-94457a00-a980-11e9-9781-f6a578e340ad.png)
![Draft](https://user-images.githubusercontent.com/1009664/61470019-9576a700-a980-11e9-8c50-cd90f45223e9.png)

**Comment by xt0rted** [comment]
The draft label text is being styled grey because `.Label--outline` is showing up after `.Label--draft`. So the grey from the outline version is taking priority.

The pre-release label is using a custom orange for the text `#f3582c` but the default border color `#f66a0a`. Do we want to use a custom color in both spots, or the default?

**Comment by silverwind** [comment]
Any example link with both tags in it?

**Comment by xt0rted** [comment]
@silverwind drafts don't look to be public, so I just sent you an invite to see it. Check https://github.com/xt0rted/invite-test/releases

**Comment by silverwind** [comment]
Thanks. Turns out a specific generator re-ordering done for mobile broke it. Given that mobile is a second-class citizen right now, I changed the order so color rules generate after grey ones, fixing this.
